step2 커밋이용~~~
wdj4606/kotlin-racingcar pull request #15
Opened 2023-11-30 12:36 UTC by YM326

휴휴 시간날때 틈틈이

2023-11-30 13:26 UTC, wdj4606 requested changes
라쿤~잘 구현해주셨네요! 👍 피드백 적어놨으니 확인 부탁드립니다 ㅎㅎ
최상위 함수로 작성해주셨는데, 각 함수들을 클래스로 분리하여 관리해보는건 어떨까요?

2023-11-30 13:26 UTC, wdj4606 commented on src/main/kotlin/step2/Calculator.kt
> +fun calcData(number1: Double, number2: Double, operator: String): Double {
기본적으로 Java 혹은 코틀린에서는 정수값에 대해선 Double이 아닌 Int로 받아야 계산하는데 오차가 나지 않아용!

2023-11-30 13:26 UTC, wdj4606 commented on src/main/kotlin/step2/Calculator.kt
> +    if (operator == "+") {
해당 부분에 있어서 operator를 enum class로 관리해보는건 어떨까여? 만약 다른 연산기호가 추가가 된다고 하면,
뒤에 else if를 계속해서 붙여주는 형태가 되니 enum class로 변경하는 것으로 해보시죠!

2023-11-30 13:26 UTC, wdj4606 commented on src/main/kotlin/step2/Calculator.kt
> +
최상위 함수로 작성해주셨군요 ㄷㄷ 역시 프론트 갓발자!
코틀린에선 `object`라는 class형태를 제공합니다. 해당 부분을 한번 찾아보시고 최상위 함수와 `object`의 차이점에 대해 알아보고 적용해보는것도 좋을거같애요!

2023-11-30 13:26 UTC, wdj4606 commented on src/main/kotlin/step2/Calculator.kt
> +    val calcItems = ArrayList<String>(data!!.split(" "))
ArrayList가 아닌 그냥 List로 받아도 좋을거 같습니다. 그리고 코틀린에서 `!!` 기호는 자바 코드를 호출하였을때 호환하기 위한 용도입니다. 이부분에 대해서는 `checkData`를 통해 null 체크가 된 data를 받아서 사용하는것도 좋을거같애요!

2023-11-30 13:26 UTC, wdj4606 commented on src/main/kotlin/step2/Calculator.kt
> +    if (data === null || data == "")
코틀린에선 `isNullOrBlank()` null과 빈값을 모두 비교해주는 함수가 있습니다! 그리고 if문을 통하여 예외를 던지는 구문은
`require(), check()`로 사용하면 좋습니다!
as - is 
```kotlin
if (data == null || data == "") throw Exception...
``` 
to - be
```kotlin
require(!data.isNullOrBlank()) {"입력값은 빈 값이 될 수 없습니다."}
```

2023-11-30 13:26 UTC, wdj4606 commented on src/main/kotlin/step2/Calculator.kt
> +    if (operators.contains(operatorItem))
이부분도 마찬가지로 require나 check로 변경할 수 있겠져?

2023-11-30 13:26 UTC, wdj4606 commented on src/main/kotlin/step2/Calculator.kt
> +fun isNumeric(s: String): Boolean {
전체적으로 `Boolean` 값을 통하여 상위 로직에서 판단하는 형태로 작성을 해주셨는데, 이 부분을 함수별로 각자가 책임지는 형태로 값을 반환하여 상위 로직에 대해 가볍게 만들어보는게 어떨까여?

2023-11-30 13:41 UTC, YM326 commented on src/main/kotlin/step2/Calculator.kt
> +
아 사실 귀찮아서 클래스 분리 안했는데,,,,,ㅋㅋㅋㅋㅋㅋㅋ 넴,,,,

2023-11-30 13:51 UTC, YM326 commented on src/main/kotlin/step2/Calculator.kt
> +    val calcItems = ArrayList<String>(data!!.split(" "))
저거 리스트로 받으면 아래에서 remove 동작 못해서 arraylist로 재선언 해놓기는 했습니다.

2023-12-01 00:45 UTC, wdj4606 commented on src/main/kotlin/step2/Calculator.kt
> +    val calcItems = ArrayList<String>(data!!.split(" "))
코틀린에선 List도 MutableList / List로 구분해서 사용합니당. List는 보통 불변객체에 해당하는 부분에 있어서 사용이 되고, MutableList는 안에 값을 변경이 가능한 부분으로 사용될때 사용되져. ArrayList는 Java에서 사용되는 부분이라 당연히 코틀린에서 사용이 가능하지만, 코틀린에서 제공하는 MutableList로 사용을 해봐도 좋을거같애요!

2023-12-02 04:01 UTC, wdj0717 approved these changes
라쿤~너무 잘 구현해주셨습니다! 
몇가지 피드백 남겼으니 확인부탁드립니다!

2023-12-02 04:01 UTC, wdj0717 commented on src/main/kotlin/step2/Calculator.kt
> +        if (operator == Opt.ADD.opt) {
제가 처음 의도했던 피드백이 잘못 전달 드렸다 보네용 ㅠ 제가 말씀드렸던건 if elseif 구문을 enum을 통하여 제거해달라는 말씀이였습니당! 해당 구문은 when문으로 변경하면 가독성이 더 좋아질거 같애요!
```kotlin
return when(operator) {
            Opt.ADD.opt -> return number1 + number2
            Opt.SUBTRACT.opt -> return number1 -  number2
            Opt.MULTIPLY.opt -> return number1 *  number2
            Opt.DIVIDE.opt -> return number1 /  number2
            else -> throw IllegalArgumentException("잘못된 연산자입니다.")
        }
```

2023-12-02 04:01 UTC, wdj0717 commented on src/main/kotlin/step2/Calculator.kt
> +    fun add(number1: Int, number2: Int): Int {
코틀린에서는 연산에 함수가 전부 적용되어 있습니다! 그러기 떄문에 +, -, *, / 를 그냥 인라인으로 명시하는게 좋아요!

2023-12-02 04:01 UTC, wdj0717 commented on src/main/kotlin/step2/Calculator.kt
> +object Calculator {
Object 클래스로 분리한거 아주 굿!

2023-12-02 04:01 UTC, wdj0717 commented on src/main/kotlin/step2/Checker.kt
> +        val operator = operators.find { item -> item.opt == operatorItem }
이부분도 하나의 구문으로 합칠수 있겠져?
```kotlin
Opt.values().find { item -> item.opt == operatorItem }
```

2023-12-02 04:01 UTC, wdj0717 commented on src/main/kotlin/step2/Checker.kt
> +object Checker {
계산하는 로직과 체크하는 로직을 나눈건 아주 좋습니다!

2023-12-02 04:01 UTC, wdj0717 commented on src/test/kotlin/step2/CalculatorTest.kt
> +    fun `덧셈`() {
해당 부분에 덧셈에 관한 테스트라고 하면, 덧셈 함수에 관한 테스트 보다
기존에 계산되는 로직에 덧셈만 넣어서 테스트 돌려보는게 훨씬 좋습니다!
```kotlin
val acutal = Calculator.calculate("2 + 3")
assertThat(acutal).isEqualTo(3)
```

2023-12-02 04:04 UTC, merged

2023-12-02 10:48 UTC, YM326 commented on src/test/kotlin/step2/CalculatorTest.kt
> +    fun `덧셈`() {
아 이 부분은 체크 없이 단순히 함수만 테스트 하려고 따로 분리한거긴 해요