Step2
wdj4606/kotlin-racingcar pull request #17
Opened 2023-12-02 07:23 UTC by creativeYS

2023-12-02 10:05 UTC, wdj4606 requested changes
챕장님! 잘 구현해주셨네요! 👍  역시 코틀린 갓발자 ㄷㄷ

몇가지 피드백 남겨놨으니 확인부탁드립니다!

2023-12-02 10:05 UTC, wdj4606 commented on src/main/kotlin/calculator/Calculator.kt
> +        var result: Double = tokens[index].toDouble()
해당 첫번째 인덱스에 숫자가 아니면 어떻게 될까용?? 숫자가 아닐때에 처리가 있어야할듯 합니당

2023-12-02 10:05 UTC, wdj4606 commented on src/main/kotlin/calculator/Calculator.kt
> +class Calculator {
함수들에 관하여 프로퍼티를 가지고 있지 않은 형태인데요. 이 부분에 관해선 object class로 변경해보는것이 어떨까요? 
싱글턴 보장까지 해줍니다!

2023-12-02 10:05 UTC, wdj4606 commented on src/main/kotlin/calculator/OperatorType.kt
> +enum class OperatorType(
eunm의 람다식을 활용해주셨네요 아주 좋습니다 👍

2023-12-02 10:05 UTC, wdj4606 commented on src/main/kotlin/calculator/OperatorType.kt
> +    private val operator: (Double, Double) -> Double
이펙티브 자바에서 말하기를 정수형 계산에 관해서 Double이나 float일 경우에는 정확한 계산이 되지 않습니다!

2023-12-02 10:05 UTC, wdj4606 commented on src/main/kotlin/calculator/OperatorType.kt
> +            return values().firstOrNull { it.symbol == symbol }
해당 부분을 find함수로 변경해볼수 있을거같애요!
```kotlin
values().find { it.symbol == symbol }
``` 
추가로 find함수 안에 있는 로직을 함수로 빼게 되었을때 추가로 OCP까지 지킬 수 있습니다!

2023-12-02 10:41 UTC, merged

2023-12-03 06:34 UTC, creativeYS commented on src/main/kotlin/calculator/Calculator.kt
> +        var result: Double = tokens[index].toDouble()
감사합니다.
숫자가 아니면 toDouble() 에서 예외를 던질 것일 것으로 기대하였습니다.

2023-12-03 06:34 UTC, creativeYS commented on src/main/kotlin/calculator/OperatorType.kt
> +    private val operator: (Double, Double) -> Double
실수계산으로 판단하였는데, 조건상 정수기준으로만 계산한다면 말씀하신대로 수정하는것이 적절하겠네요!

2023-12-03 06:40 UTC, creativeYS commented on src/main/kotlin/calculator/OperatorType.kt
> +            return values().firstOrNull { it.symbol == symbol }
감사합니다.
find  의 구현부로 가보면 firstOrNull을 호출하였고,
더불어, find, indexOf 보다는 firstOrNull 이 의미전달이 명확하다고 판단했습니당!

2023-12-03 06:44 UTC, creativeYS commented on src/main/kotlin/calculator/Calculator.kt
> +class Calculator {
오... 현재로서는 그렇게 싱글턴 처럼 간단하게 object 처리하는게 낫겠군요!
감사합니다.