step-2 first commit
wdj4606/kotlin-racingcar pull request #18
Opened 2023-12-02 08:33 UTC by 00rigin

아 코틀린 너모 자바랑 너낌이 다르다...
어색해 죽겐네...

2023-12-02 08:57 UTC, wdj4606 requested changes
쭈니 구현 아주 잘해주셨습니다! 👍 코테스트도 DCI로 해준거 아주 좋네요!
몇가지 피드백 남겼으니 확인부탁드립니다.

2023-12-02 08:57 UTC, wdj4606 commented on src/main/kotlin/step2/Utils.kt
> +class Utils {
해당 Utils는 프로퍼티에 의존하지 않고 제너럴한 함수로만 사용이 되고 있는데여. 이럴땐 object로 변경해보는건 어떨까요? 그렇게 되면 Calculator 역시 Utils의 변수를 안받아도 되고, Calculator도 역시 object로 변환할수 있겠네요!
object의 특징을 한번 찾아보시고 변경해주세요! object는 싱글턴을 보장해줍니다.

2023-12-02 08:57 UTC, wdj4606 commented on src/main/kotlin/step2/Operators.kt
> +enum class Operators(val symbol: String) {
override도 아주 좋은 선택인거 같네요! 👍 저번 이펙티브 자바에 얘기한 것처럼 Double형일땐 계산식이 정확도가 맞지 않습니당

2023-12-02 08:57 UTC, wdj4606 commented on src/main/kotlin/step2/Calculator.kt
> +        val inputList = utils.splitStringIntoArrayList(input!!)
`!!`기호는 코틀린에서 안티패턴입니당. 위에 validateInput으로 null체크가 된 input값을 반환시켜주는 형태가 되면 좋겠네요!

2023-12-02 08:57 UTC, wdj4606 commented on src/test/kotlin/step2/CalculatorTest.kt
> +internal class CalculatorTest : DescribeSpec({
DCI 코테스트 아주 굿입니다 ㅎㅎ 👍

2023-12-02 08:57 UTC, wdj4606 commented on src/main/kotlin/step2/Utils.kt
> +        if (input.isNullOrEmpty()) {
if문을 통하여 IlliegalArgumentException을 내고 있는데요.
이 부분은 코틀린에서 제공하는, `require` 함수가 있습니당
```kotlin
require(input.isNullOrEmpty()) { "Input is null or empty" }
```

2023-12-02 08:57 UTC, wdj4606 commented on src/main/kotlin/step2/Utils.kt
> +    fun splitStringIntoArrayList(input: String): ArrayList<String> {
ArrayList가 아닌 코틀린에서 제공하는 List로 변경해보는건 어떨까요? 
코틀린에선 immutable한 List와 mutable한 List로 구분해서 사용합니다!
이 차이점 확인해보시고 변경해주시면 좋을거같애요!

2023-12-02 08:57 UTC, wdj4606 commented on src/main/kotlin/step2/Utils.kt
> +    // string을 공백을 기준으로 split 하여 arraylist로 반환한다.
각 함수들에 대해선 주석을 넣어놔 주셨는데. 이거 제거가 안된거죠?ㅋㅋㅋㅋ
적절한 네이밍만 사용하면 주석을 굳이 넣어줄 필요가 없습니다.

2023-12-02 08:57 UTC, wdj4606 commented on src/test/kotlin/step2/CalculatorTest.kt
> +    describe("calculator") {
테스트 빡빡하게 아주 굿입니다!

2023-12-02 08:57 UTC, wdj4606 commented on src/main/kotlin/step2/Utils.kt
> +        return try {
try - catch에서 `NumberFormatException`을 났을때, 던지는 행위가 없이 false를 반환하고 상위 함수에서 다른 에러로 던지고 있는 형태네요. 이부분에 관해선 try - catch문 말고 다른 방식으로 풀수 있지 않을까요? 만약 숫자가 아니라면 해당 구문에서 `NumberFormatException`을 던지는게 맞다고 생각이 듭니당.

그리고 해당 함수는 Utils에서만 사용되는거 같으니 접근자도 같이 확인해주세요!

2023-12-08 09:20 UTC, 00rigin commented on src/main/kotlin/step2/Operators.kt
> +enum class Operators(val symbol: String) {
근데 나눗셈이 있는걸...ㅠㅠㅠ int나 long으로는 안되지 않을까유...ㅎ...

2023-12-08 13:42 UTC, wdj4606 commented on src/main/kotlin/step2/Operators.kt
> +enum class Operators(val symbol: String) {
나눗셈 같은 경우에만 double로 해서 변경하는 형식이 되어야할거같애요!

2023-12-08 13:43 UTC, wdj4606 approved these changes
쭈니 머지 하였으니 다음단계 진행해주시기 바랍니다!

2023-12-08 13:43 UTC, merged