* step3
wdj4606/kotlin-racingcar pull request #19
Opened 2023-12-02 09:05 UTC by creativeYS

2023-12-02 09:05 UTC, creativeYS commented
일단 작성해봄. 추후에 rebase 등으로 정리후 병합해야지...

2023-12-02 10:35 UTC, wdj4606 requested changes

2023-12-02 10:35 UTC, wdj4606 commented on src/main/kotlin/racingcar/Car.kt
> +    var position: Int = 1,
첫 Position을 1로 잡아주셨는데, 출력하는 화면에선 1부터 찍는게 아닌 0부터 찍고있습니다. 전진을 못한 상태는 출력값에 아무것도 안나와야합니다! 
그리고 매직넘버 치환해주세요!

2023-12-02 10:35 UTC, wdj4606 commented on src/main/kotlin/racingcar/Main.kt
> +    for (i in 1..inputView.tryNum) {
for문이 아닌 repeat구문으로 사용해보시는게 어떨까요?
```kotlin
repeat(inputView.tryNum) {
     race.race()...
}
```

2023-12-02 10:35 UTC, wdj4606 commented on src/main/kotlin/racingcar/Car.kt
> +    private var engine: CarEngine = CarEngine()
CarEngine이라는 객체가 변경될 여지가 있을까요? 각 Car객체마다 전략을 다르게 가져가는 것이 아닐 경우엔, 변경할 여지가 없어보입니다!

2023-12-02 10:35 UTC, wdj4606 commented on src/main/kotlin/racingcar/Race.kt
> +class Race(
Race라는 클래스가 carNum을 가지고 있는 형태입니다. 자동차 경주에 필요한 정보는 Car만 가지고 있는게 맞지 않을까여? carNum이라는건 결국 InputValue에 의존되는 형태인거 같습니다.

2023-12-02 10:35 UTC, wdj4606 commented on src/main/kotlin/racingcar/ui/ResultView.kt
> +        for (i in 1..car.position) kotlin.io.print("-")
해당 구문도 repeat으로!

2023-12-02 10:35 UTC, wdj4606 commented on src/main/kotlin/racingcar/CarEngine.kt
> +        val CAN_MOVE_READY = 4
연관 객체에 상수로 해당하는 부분은 const 구문을 사용해주세요!
컴파일시 값이 할당됩니다.

2023-12-02 10:35 UTC, wdj4606 commented on src/main/kotlin/racingcar/CarEngine.kt
> +        return Random.nextInt(10) >= CAN_MOVE_READY
`10`이라는 상수 자체도 매직넘버 치환해주세요!

2023-12-02 10:35 UTC, wdj4606 commented on src/test/kotlin/racingcar/CarTest.kt
> +class CarTest {
다음 단계부터 kotest로 사용해 보는건 어떨까요??

2023-12-02 10:35 UTC, wdj4606 commented on src/test/kotlin/racingcar/CarTest.kt
> +        val engine = mockk<CarEngine>()
mock객체를 이용한거 아주 좋습니다! 👍

2023-12-02 10:35 UTC, wdj4606 commented on src/test/kotlin/racingcar/CarTest.kt
> +}
CarEngine canMove()에 대한 테스트 코드는 빠져있는거 같습니다!

2023-12-02 10:35 UTC, wdj4606 commented on src/test/kotlin/racingcar/RaceTest.kt
> +    fun `자동차 이동 테스트 갈 수 있을 때`() {
테스트 네이밍이 조금 모호한거 같습니다. 자동차 경주에 관한 테스트인거 같은데 아닌가여??

2023-12-02 10:35 UTC, wdj4606 requested changes
챕장님 step3도 잘 구현해주셨네요! step2 완료되시면 바로 진행해주시면 되겠습니다 ㅎㅎ

2023-12-03 06:47 UTC, creativeYS commented on src/main/kotlin/racingcar/Car.kt
> +    var position: Int = 1,
- 매직넘버는 companion 사용하여 정의하였습니다.
- 그런데, 0부터 찍는건 요구사항에 잘 드러나지 않아서.. 0일때 진행률 (-) 표시를 해준다고 보고 수정하도록 하겠습니다.

2023-12-03 06:50 UTC, creativeYS commented on src/main/kotlin/racingcar/Main.kt
> +    for (i in 1..inputView.tryNum) {
오우 좋으네용!
코틀린은 특별히 언급하지 안하도 it 로 받을 수 있는,
심플하게 표혀나능한  미리 정의된 함수들이 많아서 참 좋은거 같습니다. 감사합니다.

2023-12-03 06:51 UTC, creativeYS commented on src/main/kotlin/racingcar/Car.kt
> +    private var engine: CarEngine = CarEngine()
추후 어떻게 요구사항이 발생할지 몰라서 CarEngine 차가 이동하는 규칙이 바뀔 여지가 있다고 보았습니다.
어떤요구사항이 있을지 모르니 그냥 상상해서 확장성을 대비해 만들어 본겁니다.ㅋㅋㅋ

2023-12-03 06:58 UTC, creativeYS commented on src/main/kotlin/racingcar/Race.kt
> +class Race(
맞습니다. 그래서 var/val 이 아닌 생성자 param 으로만 받고, 외부에서는 사용할 수 없는 형태로 구성하였습니다.
따라서 생각하는 것 처럼 Race 클래스는 carNum을 가지고 있지 않는 것으로 알고있습니다.
![Uploading image.png…]()

2023-12-03 07:01 UTC, creativeYS commented on src/main/kotlin/racingcar/ui/ResultView.kt
> +        for (i in 1..car.position) kotlin.io.print("-")
position 이 0 일때 - 표시를 안하면 티가 안나서.. 임의로 repeat 변경후 1을 더해 표현하였습니다.
감사합니다.

2023-12-03 07:03 UTC, creativeYS commented on src/test/kotlin/racingcar/CarTest.kt
> +}
이게 어제 한참을 시도해봤는데.. mockkstatic 이 Random 클래스에 대해서는 동작은 안하더군요... 왜지... 아직 답을 못찾았는데,
localdate, instance 등 다양한데에서는 잘 mock 주입이 가능한데, 왜 Random에서는 에러가 날까요... ㅜ

every {...} 구문에서 every 내부 함수가 Mock 객체여야 한다는 에러가 나오고있네용..

2023-12-03 07:04 UTC, creativeYS commented on src/test/kotlin/racingcar/CarTest.kt
> +class CarTest {
그러도록 하겠습니다.

2023-12-03 07:04 UTC, creativeYS commented on src/main/kotlin/racingcar/CarEngine.kt
> +        return Random.nextInt(10) >= CAN_MOVE_READY
감사합니다.

2023-12-03 07:06 UTC, creativeYS commented on src/test/kotlin/racingcar/RaceTest.kt
> +    fun `자동차 이동 테스트 갈 수 있을 때`() {
복붙하다보니 이름갱신을 놓쳤네요 ㅜ
감사합니다.

2023-12-03 07:31 UTC, wdj4606 commented on src/test/kotlin/racingcar/CarTest.kt
> +}
<img width="357" alt="image" src="https://github.com/wdj4606/kotlin-racingcar/assets/151616407/639542db-9358-4f21-8853-09d4b88c1c8a">
음..아마 Random클래스가 다른 Random클래스를 import하여 mock객체가 생성되어 그런거 같은데요! 다시 한번 확인해주시면 좋을거같습니다!

2023-12-03 07:34 UTC, wdj4606 approved these changes
챕장님 피드백 반영 잘해주셨습니다! 👍 
몇가지 피드백 남겼으니 확인해주시고 다음단계 진행해주시면 되겠습니다 😄

2023-12-03 07:34 UTC, merged

2023-12-03 07:37 UTC, wdj4606 commented on src/main/kotlin/racingcar/Race.kt
> +    val cars: List<Car> = (1..carNum).map { Car() }
해당 부분을  `List(carNum) { Car() }` 요런 식으로도 표현이 가능합니다!

2023-12-03 07:40 UTC, creativeYS commented on src/test/kotlin/racingcar/CarTest.kt
> +}
!!? 감사합니다!

2023-12-03 07:45 UTC, creativeYS commented on src/main/kotlin/racingcar/Race.kt
> +    val cars: List<Car> = (1..carNum).map { Car() }
오... 역시 코틀린... 너무 심플하고 이쁘게 표현되는군요...!

2023-12-03 08:03 UTC, creativeYS commented on src/test/kotlin/racingcar/CarTest.kt
> +}
아.. 원인은 Random 에 Default companion 을 mock 처리해야하는 것이었습니다...
이후 코드에 적용함!