step3 커밋이용~~~
wdj4606/kotlin-racingcar pull request #20
Opened 2023-12-02 10:51 UTC by YM326

step3 커밋이용~~~

2023-12-02 11:14 UTC, wdj4606 requested changes
라쿤~잘 구현해주셨습니다! 👍  
피드백 몇개 남겼은니 확인 부탁드려요!

2023-12-02 11:14 UTC, wdj4606 commented on src/main/kotlin/step3/CarRacing.kt
> +object CarRacing {
전첵적으로 View를 찍는 로직과 자동차가 움직이는 로직이 같이 있습니다 😱
출력하는 로직과 자동차 움직이는 로직을 분리해보는건 어떨까요?
자동차가 움직이는 로직은 Car라는 클래스나 다른 방식에 자동차에 대한 객체를 생성하여 로직을 분리시켜주세요!

2023-12-02 11:14 UTC, wdj4606 commented on src/main/kotlin/step3/CarRacing.kt
> +        for (i in 0 until inputItem.tryCount) {
해당 for문을 repeat함수로 사용할 수 있습니다!
```kotlin
repeat(inputItem.tryCount) {
    goRacing()
}
```

2023-12-02 11:14 UTC, wdj4606 commented on src/main/kotlin/step3/CarRacing.kt
> +        for (i in 0 until carList.size) {
여기도 마찬가지입니다!

2023-12-02 11:14 UTC, wdj4606 commented on src/main/kotlin/step3/CarRacing.kt
> +        carList[index] += "-"
해당 "-"이라는건 출력하는 곳에서의 로직이지 않을까여?

2023-12-02 11:14 UTC, wdj4606 commented on src/test/kotlin/step3/CarRacingTest.kt
> +    fun `레이싱,,`() {
ㅋㅋㅋㅋㅋㅋ 위에 피드백 남긴거처럼 로직이 분리가 제대로 안되서 테스트하기가 어려울거에요 ㅋㅋㅋ
먼저 분리작업을 해주시면서 수정하면 테스트하기 쉬울겁니다!

2023-12-03 06:05 UTC, YM326 commented on src/test/kotlin/step3/CarRacingTest.kt
> +    fun `레이싱,,`() {
아 테스트가 익숙하지 않다보니 랜덤값이 들어가는 항목에 대한 테스트가 애매한 느낌이에요ㅋㅋㅋ

2023-12-03 06:05 UTC, YM326 commented on src/main/kotlin/step3/CarRacing.kt
> +        carList[index] += "-"
car racing이 그냥 움직이는걸 데이터 쌓는 느낌으로 넣었어서 이건 데이터 넣는 거라 생각했는데 
피터는 이것도 뷰라는 개념으로 가져가는게 좋으신건가요??

2023-12-03 07:18 UTC, wdj4606 commented on src/main/kotlin/step3/CarRacing.kt
> +        carList[index] += "-"
만약 "-"이 값을 다른 값으로 변경해서 출력한다 라고하면 다른 개발자가 수정을 진행한다고 했을때, 어느 부분을 먼저 확인을 할까요? 출력되는 값이 다른 값으로 변경을 한다고 하였을때 출력되는 로직을 먼저 확인해보지 않을까여? 그래서 말씀드린 부분이였습니당

2023-12-03 07:57 UTC, YM326 commented on src/main/kotlin/step3/CarRacing.kt
> +        carList[index] += "-"
이게 뭔가 프론트랑 백의 관점 차이인거 같네욬ㅋㅋㅋㅋㅋ 
프론트는 뷰라고 생각하면 데이터는 별도고 단순히 진짜 데이터를 보여준다 느낌으로 생각되서ㅋㅋㅋ

데이터를 어떻게 들고있냐의 관점에서 다르게 해석될 수 있을 것 같긴한데,
피터의 의견도 그렇긴 하네요ㅋㅋ
수정하겠습니다

2023-12-03 08:37 UTC, wdj4606 commented on src/main/kotlin/step3/CarRacing.kt
> +        carList[index] += "-"
음 라쿤이 말씀한 내용은 무슨 말인지 이해는 합니당. 만약 데이터는 별도의 느낌이라고 생각을 하신다면,
Result객체가 있어야겠지요. 자동차 경주를 하였을때의 나온 결과값에 대한 객체.  자동차 경주를 수행하고 나온 데이터를 가지고 만든 결과값의 객체. 이러한 형태라고 생각이 드네요. 현재는 직접 자동차 경주를 수행하는 로직에 해당 부분이 포함이 되어있다라는게 문제여서 말씀드렸던 부분이였는데여. 라쿤이 말씀하신 부분도 맞는말입니다!

2023-12-04 11:42 UTC, wdj4606 approved these changes
라쿤! step3 피드백 반영하는데 아마 많이 힘드셨을거 같애요 ㅠ 머지하였으니,
다음단계 진행해주시면 되겠습니다!

2023-12-04 11:42 UTC, merged