feature : 1. 자동차 경주 - 2단계. 문자열 계산기
wdj4606/kotlin-racingcar pull request #25
Opened 2023-12-04 11:20 UTC by mayomayo0623

@wdj4606 첫 번째 숙제를 이제 하네요ㅠ 너무 늦어서 죄송합니다.
리뷰 부탁 드립니다. 감사합니다:)

2023-12-04 11:40 UTC, wdj4606 requested changes
대현님! 2단계 잘 구현해주셨습니다! 👍 
몇가지 피드백 남겼으니 확인부탁드립니다!

2023-12-04 11:40 UTC, wdj4606 commented on README.md
> +## checklist
오우 README 작성 너무 좋습니다! 👍 
`- [O]` 이부분을 - [x] 로 표현해주시면 좀 더 이쁘게 변환됩니다ㅎㅎ

2023-12-04 11:40 UTC, wdj4606 commented on src/main/kotlin/calculator/main/Main.kt
> +fun main(args: Array<String>) {
main함수를 작성해주셨는데, 2단계는 굳이 main으로 출력을 안해주셔도 됩니다!

2023-12-04 11:40 UTC, wdj4606 commented on src/main/kotlin/calculator/service/CalculateService.kt
> +        if (input.isEmpty()) {
메인 함수가 없어진다고 하면 `isNullOrBlank()` 함수로 null과 빈값을 모두 체크할 수 있을겁니다!
그리고 if문을 통한 Exception을 던지는 형태인데요.
코틀린에서는 이 부분을 `require(), check() `함수로 제공합니다.
`require(!input.isNullOrBlank()) { "input error" }`

2023-12-04 11:40 UTC, wdj4606 commented on src/main/kotlin/calculator/service/CalculateService.kt
> +        if (expressions.size % 2 == 0) {
여기도 마찬가지로 require함수를 쓰면 되겠죠!

2023-12-04 11:40 UTC, wdj4606 commented on src/main/kotlin/calculator/service/calculator/Operations.kt
> +class Addition : Operation {
현재 연산자별로 연산자에 대해서 클래스로 정의해주셨는데요. 
코틀린에서 enum class를 제공합니다.
```kotlin
enum class Operation(val value: String, val operate: (Int, Int) -> Int {
ADD("+", { x, y -> x + y }),
SUBSTRACT
...
``` 
enum class로 이렇게 람다와 같이 사용을 하게 된다면 Operation 인터페이스도 필요 없어지겠져??

2023-12-04 11:40 UTC, wdj4606 commented on src/main/kotlin/calculator/service/CalculateService.kt
> +    private val operations = mapOf(
이쪽 부분을 enum class를 활용하면 좀 더 간결하게 변경 될 수 있을겁니다!
만약 연산자가 1개 더 추가가 된다고 가정을 해봤을때, enum class에서만 명시를 해주면 되는거니깐요 ㅎㅎ

2023-12-04 11:40 UTC, wdj4606 commented on src/test/kotlin/step2/CalculateServiceTest.kt
> +    }
연산자가 하나일때에 대한 테스트, 연산자가 두개일때에 대한 테스트 이런식으로 테스트 코드가 좀 더 있으면 좋겠습니다!
`2+3, 2+3*4, 2+3-1` 요런식으로요!

2023-12-04 11:40 UTC, wdj4606 commented on src/main/kotlin/calculator/service/CalculateService.kt
> +class CalculateService {
프로퍼티를 의존하지 않는 class를 만들어 주셨는데요. 이럴 경우엔 object를 사용해보시는게 어떨까요?
object의 특징도 한번 찾아보시면 좋을거 같애요! object class는 싱글턴을 보장해줍니다!

2023-12-04 11:40 UTC, wdj4606 commented on src/main/kotlin/calculator/service/calculator/Operations.kt
> +    override fun calculate(left: Double, right: Double): Double {
자바와 코틀린에선 Double형,Float형 연산자는 정확한 계산이 되지 않습니다! 정수형에 관한 연산은 Int나 Long형인 정수형 타입으로 연산을 해주셔야 정확한 계산이 됩니다!

2023-12-04 12:33 UTC, mayomayo0623 commented on src/main/kotlin/calculator/service/CalculateService.kt
> +        if (input.isEmpty()) {
좋네요! 코틀린은 항상 간결함을 지향하는 것 같아요.

2023-12-04 12:38 UTC, mayomayo0623 commented on src/main/kotlin/calculator/service/CalculateService.kt
> +    private val operations = mapOf(
enum class 를 쓰면 좋은 이유가 확실해졌네요!

2023-12-04 12:39 UTC, mayomayo0623 commented on src/main/kotlin/calculator/service/CalculateService.kt
> +class CalculateService {
진짜 편하네요:) C++ 생각하면 후..

2023-12-04 12:40 UTC, mayomayo0623 commented on src/main/kotlin/calculator/service/calculator/Operations.kt
> +    override fun calculate(left: Double, right: Double): Double {
헉 정확한 실수 계산을 해야 될 때는 관련 문서를 더 찾아 봐야 되겠네요!

2023-12-04 12:41 UTC, mayomayo0623 commented
@wdj4606 리뷰 해 주신 것 모두 반영하였습니다.

2023-12-05 00:59 UTC, wdj4606 approved these changes
피드백 반영 너무 빨리 해주셨네요 ㄷㄷ 👍 
머지할테니 피드백 확인해주시고 다음 단계 진행해주시기 바랍니다 ㅎㅎ

2023-12-05 00:59 UTC, wdj4606 commented on src/main/kotlin/calculator/service/CalculateService.kt
> +        require(!input.isNullOrBlank()) { throw IllegalArgumentException("input error") }
require 구문 함수 안을 들어가보시면 기본적으로 `IllegalArgumentException` 을 던지는 형태로 되어있습니다! 그래서 { } 안에서 exception을 던지는 형태가 아닌 에러 메시지 구문만 넣어주면 `IllegalArgumentException`으로 던져줍니다!
<img width="458" alt="image" src="https://github.com/wdj4606/kotlin-racingcar/assets/151616407/15b2d999-5dea-44b0-ae99-5f72a34dd64d">

`require(!input.isNullOrBlank()) { "input error" }`

2023-12-05 00:59 UTC, wdj4606 commented on src/main/kotlin/calculator/service/CalculateService.kt
> +        require(expressions.size % 2 != 0) { throw IllegalArgumentException("input error") }
여기도 마찬가지!

2023-12-05 00:59 UTC, merged