step2 문자열 계산기 구현
wdj4606/kotlin-racingcar pull request #28
Opened 2023-12-05 08:02 UTC by pdg0704

2023-12-09 03:43 UTC, wdj4606 requested changes
동근님! 구현 잘해주셨습니다! 👍  
몇가지 피드백 남겼으니 확인부탁드립니다!

2023-12-09 03:43 UTC, wdj4606 commented on src/main/kotlin/step2/Calculator.kt
> +data class Calculator(val input: String = "") {
data class를 사용한 이유가 있나요?

2023-12-09 03:43 UTC, wdj4606 commented on src/main/kotlin/step2/Calculator.kt
> +        if (list.size < 3) {
if문을 통하여 `IllegalArgumentException`을 던지는 구문으로 작성해주셨는데여. 
코틀린에선 `require(), check()` 함수를 제공합니다!
`require(list.size >=3) { "입력 값이 올바르지 않습니다" }`

2023-12-09 03:43 UTC, wdj4606 commented on src/main/kotlin/step2/Calculator.kt
> +        if (list.size % 2 == 0) {
여기도 마찬가지겠죠? 😄

2023-12-09 03:43 UTC, wdj4606 commented on src/main/kotlin/step2/Calculator.kt
> +            list.removeAt(1)
반복되는 구문들은 함수로 빼서 관리해보는게 어떨까요?? 🤔

2023-12-09 03:43 UTC, wdj4606 commented on src/main/kotlin/step2/Calculator.kt
> +        if (!isNumeric(x) || !isNumeric(y)) {
x랑 y값이 숫자이냐 라는 형태에 함수를 통하여 exception을 던지고 있는데요.
해당 exception은 isNumeric이라는 함수에서 책임을 지는게 맞지 않을까요? 🤔 
그렇게 되면 숫자일땐 Int형으로 반환하고 숫자가 아닐땐 exception을 던져 아래 코드에서 연산할때 좀 더 편하게 할 수 있을거같습니다!

2023-12-09 03:43 UTC, wdj4606 commented on src/main/kotlin/step2/Calculator.kt
> +    private fun add(x: String, y: String): String {
코틀린에선 연산자 기호에 함수가 설정이 되어있어서 따로 함수를 만들어서 사용하시는거 보다 인라인으로 작성해 주시는게 더 좋습니다!

2023-12-09 03:43 UTC, wdj4606 commented on src/test/kotlin/step2/calculator.kt
> +}
2단계 프로그램 최종 목표 요구사항이 사칙연산 계산 우선순위는 무시한다. 라는 형태에 테스트 코드가 빠져있는거 같습니다! 현재 연산자 1개일 경우만 작성을 해주셨는데, 우선순위가 무시되는 형태에 테스트 코드를 작성해주세요!

2023-12-09 13:14 UTC, pdg0704 commented on src/main/kotlin/step2/Calculator.kt
> +data class Calculator(val input: String = "") {
이전 예제에서 수정해서 그렇습니다ㅎ 제거하겠습니다.

2023-12-10 07:15 UTC, wdj4606 approved these changes
동근님~피드백 반영 너무 잘해주셨습니다! 👍 
머지할테니 다음단계 바로 진행해주시면 되겠습니다!

2023-12-10 07:15 UTC, merged