Step2 대학생으로 돌아간 것 같슴미다
wdj4606/kotlin-racingcar pull request #29
Opened 2023-12-05 11:49 UTC by begrey

ko - test 신기하네요

2023-12-06 10:19 UTC, wdj4606 requested changes
클로이 구현 잘해주셨습니다! 👍 
몇가지 피드백 남겼으니 확인부탁드려요~

2023-12-06 10:19 UTC, wdj4606 commented on src/main/kotlin/step2/Calculator.kt
> +object Calculator {
object 클래스 아주 좋습니다! 👍

2023-12-06 10:19 UTC, wdj4606 commented on src/main/kotlin/step2/Calculator.kt
> +    private fun Double.plus(operand: Double) = this + operand
기본적으로 코틀린에서는 기호 연산자 `+, - , * , /` 에 인라인 함수가 셋팅되어 있습니다. 그러기 때문에 연산자 기호를 인라인으로 작성해주시는게 좋아요!

2023-12-06 10:19 UTC, wdj4606 commented on src/main/kotlin/step2/Calculator.kt
> +    fun calculate(operand: Double, total: Double, operator: String): Double {
operator 연산을 함수로 구현해 주셨는데요. 해당 부분을 enum으로 관리해보는거 어떨까요? 만약 여기서 연산자 기호가 하나 더 추가가 된다고 하면 해당 클래스에서 추가가 발생을 해야하는 상황인거 같습니당. `Calculator `클래스는 계산만 하는 방식이 좋을거 같애요!

2023-12-06 10:19 UTC, wdj4606 commented on src/main/kotlin/step2/Calculator.kt
> +fun main(args: Array<String>) {
2단계에선 main함수 구현을 안해주셔도 됩니다! 현재 어떻게 main함수 안에서 input값에 대한 숫자 가져오기, 연산자 가져오기에 대한 로직이 포함되어 있는데 이부분도 추상화해서 테스트 코드 작성해주시는게 좋을거 같습니다!

2023-12-06 10:19 UTC, wdj4606 commented on src/main/kotlin/step2/Calculator.kt
> +    if (args.isEmpty()) {
if문을 통하여 Exception을 던지는 형태를 만들어주셨는데요. 
코틀린에서는 해당 구문을 `require(), check()` 함수로 제공합니다.

require(!ars.isEmpty()) { "입력값은 필수입니다." }

2023-12-06 10:19 UTC, wdj4606 commented on src/main/kotlin/step2/Calculator.kt
> +    var total = inputList[0].toDouble()
만약 첫번째 인자가 숫자가 아닐경우에는 어떻게 될까용??

2023-12-06 10:19 UTC, wdj4606 commented on src/main/kotlin/step2/Calculator.kt
> +    val numberElements = inputList.filterIndexed { index, _ -> index % 2 == 0 && index != 0 }
filterIndexed 사용 아주 좋습니다! 👍

2023-12-06 10:19 UTC, wdj4606 commented on src/main/kotlin/step2/Calculator.kt
> +    for (i in numberElements.indices) {
단순 for문이 아닌 forEach문으로 변경해서 사용되는게 좀 더 가독성에 좋을거 같습니다!

2023-12-06 10:19 UTC, wdj4606 commented on src/main/kotlin/step2/Calculator.kt
> +        val operand = numberElements[i].toDoubleOrNull() ?: throw IllegalArgumentException("피연산자가 올바른 형식이 아닙니다.")
이펙티브 자바에서 아시겠지만, 정수형 계산에 관해서는 Double Float형에 대해선 정확한 계산이 되지 않습니다! 정수형인 Int, Long형으로 계산해야 정확한 계산이 됩니다!

2023-12-06 10:19 UTC, wdj4606 commented on src/test/kotlin/step2/CalculatorTest.kt
> +class CalculatorTest : DescribeSpec({
DCI패턴 아주 굿입니다! 👍

2023-12-06 10:19 UTC, wdj4606 commented on src/test/kotlin/step2/CalculatorTest.kt
> +    describe("Calculator") {
기본적인 DCI 패턴 규칙을 지켜주세용. describe -> context -> it 순입니다.
기본적으로 DCI패턴의 핵심 키워드는
1. Describe - 설명할 테스트를 명시한다.
2. Context - 테스트를 하는 상황을 기술한다.
3. It - 테스트 대상의 행동을 기술한다.

이렇게 입니다.

2023-12-11 11:16 UTC, begrey commented on src/main/kotlin/step2/Calculator.kt
> +    fun calculate(operand: Double, total: Double, operator: String): Double {
분리하여 작성해보겠습니다~~

2023-12-11 11:17 UTC, begrey commented on src/main/kotlin/step2/Calculator.kt
> +    if (args.isEmpty()) {
오오... 이렇게 한줄로..

2023-12-11 11:17 UTC, begrey commented on src/main/kotlin/step2/Calculator.kt
> +    var total = inputList[0].toDouble()
아이고 ㅋㅋ 추가하겠습니다!

2023-12-11 12:07 UTC, wdj4606 approved these changes
클로이 너무 피드백 반영 잘해주셨습니다! 👍 
머지할테니 다음단계 진행해주세요!

2023-12-11 12:07 UTC, wdj4606 commented on src/main/kotlin/step2/Operator.kt
> +    private val operator: (Long, Long) -> Long
크 아주 좋습니다!

2023-12-11 12:07 UTC, merged