Step3
wdj4606/kotlin-racingcar pull request #31
Opened 2023-12-08 10:52 UTC by mayomayo0623

스승님의 노고에 늘 감사드리며..
3단계 - 자동차 경주 pr 입니다.

2023-12-09 04:08 UTC, wdj4606 requested changes
대현님 구현 너무 잘해주셨습니다! 👍 몇가지 피드백 남겼으니 확인부탁드려요!

2023-12-09 04:08 UTC, wdj4606 commented on src/main/kotlin/racingcar/service/Car.kt
> +        return (Math.random() * 10).toInt() >= 4
해당 Random부분을 `Random().nextInt(10)` 이런식으로도 변경 할 수 있습니다 ㅎㅎ
4라는 숫자도 만약 5이상부터 움직여야한다는 요구사항이 들어올수도 있겠죠??

2023-12-09 04:08 UTC, wdj4606 commented on src/main/kotlin/racingcar/service/Car.kt
> +    var position: Int = 0
현재 0이라는 값은 우리가 알고 있는 초기값. 이라고 생각을 해주신거 같은데요. 만약 초기값이 0이 아닐 경우엔 해당 원시값을 전부 변경해줘야하는 일이 발생할 수 있습니다! 매직넘버를 치환해주시면 좋을거같애요!
연관객체로 전부 치환해주세요!

2023-12-09 04:08 UTC, wdj4606 commented on src/main/kotlin/racingcar/service/Racing.kt
> +    fun run(numberOfCar: Int, numberOfRound: Int): List<Car> {
현재 Racing이라는 클래스는 Input값과 Output값에 대하여 호출하여 각 도메인을 호출하는 Controller역할을 하는 것처럼 보입니다. 하지만, 해당 클래스에 Car리스트에 해당하는 도메인로직이랑 섞여있는 형태이네요.
껍데기 list를 만들어서 List<Car>를 생성하고 해당 List<Car>를 순회하면서 move를 하는 형태를 만들어 주셨는데요. 이렇게 되버리면 테스트 코드 작성하시는데 아마 많은 어려움이 있으셨을겁니다.
해당 부분을 List<Car>를 변수를 가지고 있는 클래스를 생성하여 해당 클래스에 이 도메인 로직을 위임해보는건 어떨까요? 우리는 이러한 클래스는 '**일급 컬렉션**'이라고 부릅니다.

2023-12-09 04:08 UTC, wdj4606 commented on src/main/kotlin/racingcar/service/Racing.kt
> +        for (i in 1..numberOfRound) {
해당 부분을 repeat함수를 사용하면 좀 더 간결하게 할 수 있습니다!
```
repeat(numberOfRound) {
    carList.map { it.move() }
}
```

2023-12-09 04:08 UTC, wdj4606 commented on src/main/kotlin/racingcar/ui/ResultView.kt
> +        for (car in carList) {
여기도 마찬가지로 repeat함수 사용하면 좋습니다!

2023-12-09 04:08 UTC, wdj4606 commented on src/test/kotlin/step3/RacingCarTest.kt
> +class RacingCarTest {
현재 전체적인 Racing을 하는 테스트 코드만 작성해 주셨는데요. 
각 도메인 별로의 단위 테스트가 있어야할 것으로 보여요! Car클래스에 대한 단위 테스트 등등 있어야 할 것으로 보입니다!

2023-12-09 04:08 UTC, wdj4606 commented on src/test/kotlin/step3/RacingCarTest.kt
> +    fun printResult() {
지금 현재 Racing이라는 클래스에서 입출력 로직에 의존되는 형태라서 해당 부분을 테스트 코드로 작성해주신거 같습니당. 도메인이 input과 output에 의존되지 않게끔 해주신다면 해당 테스트 부분도 필요 없어질겁니다! 그냥 main함수에서 입출력 호출하고 도메인 로직을 호출하는 형식으로 해주셔도 좋습니다 ㅎㅎ

2023-12-11 12:51 UTC, mayomayo0623 commented on src/main/kotlin/racingcar/service/Car.kt
> +    var position: Int = 0
@wdj4606 연관 객체로 치환해 달라는 말씀이 companion object 를 이용하라는 의미가 맞을까용?
일단, 그렇게 해봤습니다.

2023-12-11 12:59 UTC, mayomayo0623 commented on src/main/kotlin/racingcar/ui/ResultView.kt
> +        for (car in carList) {
@wdj4606 c++ 에서는 열거형 구조체를 순환할 때, 반복문에 숫자를 쓰거나 (repeat(carList.size)), index 로 배열 요소에 접근 (carList[it]) 하는 것이 오류를 유발할 가능성이 있어 지양하는 추세이기 때문에, range based for 문이 선호 되고 있습니다.
코틀린에서는 for (car in carList) 로 { } 안에서 index 접근자 없이 car 를 사용하는 것의 장점은 상관 없이 repeat 를 선호하는 편인가용?

2023-12-11 13:03 UTC, mayomayo0623 commented on src/test/kotlin/step3/RacingCarTest.kt
> +    fun printResult() {
@wdj4606 스승님! 이 부분이 잘 이해가 되지 않습니다ㅠ
말씀해 주신 대로 리펙토링 했지만, 여전히 Resultview 의 출력에 대한 test 는 필요한 것 아닌가용?

2023-12-11 13:10 UTC, wdj4606 commented on src/main/kotlin/racingcar/service/Car.kt
> +    var position: Int = 0
넵 맞습니다!

2023-12-11 13:27 UTC, wdj4606 approved these changes
대현님! 피드백 반영 너무 잘해주셨습니다! 👍 
머지할테니 피드백과 코멘트 확인해주시고 다음단계 진행해주세요!

2023-12-11 13:27 UTC, wdj4606 commented on src/main/kotlin/racingcar/service/RacingRule.kt
> +    companion object {
특정 클래스를 만들어서 모아두기 보단 사용하는 클래스에서 연관객체로 관리하는것이 좋습니다! 이렇게 해당 클래스로 모아두게 되버리난 경우는 general하게 사용되는 경우 아니면 지양합니다!

2023-12-11 13:27 UTC, wdj4606 commented on src/main/kotlin/racingcar/ui/ResultView.kt
> +        for (car in carList) {
제가 조금 짧게 생각했던거 같습니다! 만약 말씀해주신 부분대로에 관련된거면 repeat이 아닌 forEach문을 사용해도 좋을거같습니다! 코틀린에선 forEach문은 순서가 있는 컬렉션에 대한 확장함수로 제공해줍니다!
```Kotlin
carList.forEach {
…
```

2023-12-11 13:35 UTC, wdj4606 commented on src/test/kotlin/step3/RacingCarTest.kt
> +    fun printResult() {
프로그래밍 요구사항에도 명시되어 있지만 입출력 로직에 관한 부분에 대해선 테스트 코드 제외라고 적혀있을겁니다!
만약 피드백 반영하기 전에 대현님에 코드에선 어땠을까요?  Racing라는 객체에 input값을 받아오는 로직, 실제로 경주가 되는 도메인 로직, 그리고 마지막 결과값을 출력하려는 로직 이 3개가 섞여있는 형태였습니다. 그러다보니 테스트 코드를 작성해주신게 아닌가 하는 생각이 들었던거죠. 하지만 현재에 구조는 각 도메인에서 해당하는 로직들은 전부 단위테스트 형태로 분리하여 테스트를 할수 있는 형태가 되었고, 최종적으로 main이나 혹은 controller에서 input과 output에 도메인을 연결해주는 형태로 변경되었습니다!
우리가 출력을 하는데에 있어서 “-“으로 찍을건지 다른것으로 찍을건지 중요한게 아닌거지요. 결국 자동차 객체가 움직였냐 안움직였냐에 대해서 position값에 대한 로직이 중요한거지, 어떠한 방식이든지 출력은 하기만하면 되는거니깐요 ㅎㅎ

2023-12-11 13:38 UTC, merged

2023-12-11 13:46 UTC, wdj4606 commented on src/test/kotlin/step3/RacingCarTest.kt
> +        repeat(numberOfCar) {
아 이부분도 forEach로 변경해주시면 됩니다 ㅎㅎ

2023-12-13 10:51 UTC, mayomayo0623 commented on src/test/kotlin/step3/RacingCarTest.kt
> +        repeat(numberOfCar) {
너무 편리하네요! 좋습니다:)

2023-12-13 10:51 UTC, mayomayo0623 commented on src/test/kotlin/step3/RacingCarTest.kt
> +    fun printResult() {
상세한 설명 감사합니다!