Step3 자동차 경주
wdj4606/kotlin-racingcar pull request #35
Opened 2023-12-10 22:43 UTC by pdg0704

2023-12-11 11:57 UTC, wdj4606 requested changes
동근님! 3단계 구현 잘해주셨네요 👍 
저한테 private 함수 테스트 관련해서 여쭤보신 이유를 알겠습니다 ㅎㅎ
몇가지 피드백 남겼으니 확인부탁드립니다!

2023-12-11 11:57 UTC, wdj4606 commented on src/main/kotlin/Controller/RacingController.kt
> +    private
접근자 코드에 line break가 들어가있는거 같네요! 해당 부분 확인부탁드립니다!

2023-12-11 11:57 UTC, wdj4606 commented on src/main/kotlin/Controller/RacingController.kt
> +    }
만들어주신 부분이 Controller에서 MutableList의 MutableList로 같은 자료구조가 두 번 반복되는 형태인거 같습니다 😢 해당 부분을 Car 클래스에 position이라는 값을 생성하여 해당 부분에 있어서 자동차 클래스가 가지고 있는 형태로 만들어 보는건 어떨까요?

2023-12-11 11:57 UTC, wdj4606 commented on src/main/kotlin/Controller/RacingController.kt
> +        for (i in 1..race.participant.size) raceLog[0].add(0)
해당 부분에 있어서 코틀린에선 repeat 함수로 작성할 수 있습니다!
```Kotlin
repeat(race.participant.size) {
raceLog[0].add(0)
}
```

2023-12-11 11:57 UTC, wdj4606 commented on src/main/kotlin/Controller/RacingController.kt
> +    fun moveForward(car: Car): Int { // 뭔가 차량 별 능력 같은게 생기지 않을까 ㅇ3ㅇ
해당 함수는 랜덤값에 대해서 자동차가 움직이는 함수처럼 보이는데용
이 부분은 Car클래스가 책임을 지는 형태가 맞지 않을까용? 🤔

2023-12-11 11:57 UTC, wdj4606 commented on src/main/kotlin/Model/Car.kt
> +data class Car(val id: String)
id라는 프로퍼티는 무슨 용도로 만들어주신건가요? 단순 궁금해서 물어봅니다!

2023-12-11 11:57 UTC, wdj4606 commented on src/main/kotlin/View/InputView.kt
> +    fun inputNumberOfCars() {
해당 함수를 통해서 값을 저장하고 있는 형태가 아닌 바로 반환하는 값으로 변경해보는건 어떨까요?
그렇게 되면 get함수는 사용 안해도 될거같습니다!

2023-12-11 11:57 UTC, wdj4606 commented on src/main/kotlin/View/ResultView.kt
> +class ResultView(val raceLog: MutableList<MutableList<Int>>) {
입출력에 관하여 도메인 로직과 분리 잘해주셨네요! 👍

2023-12-11 11:57 UTC, wdj4606 commented on src/test/kotlin/Controller/RacingControllerTest.kt
> +class RacingControllerTest {
해당 부분에 있어서 Controller 클래스에서 해당 기능을 책임을 지고 있다보니 이러한 전체적인 테스트가 될 수 밖에 없는 형태입니다 ㅎㅎ
해당 클래스 함수를 위임하다 보시면 도메인 분리도 자연스럽게 되면서 테스트 코드 역시 작성하기 편하게 되실거 같습니다!

2023-12-11 23:14 UTC, pdg0704 commented on src/main/kotlin/Controller/RacingController.kt
> +    }
오오 이해가 되었습니다!

2023-12-11 23:15 UTC, pdg0704 commented on src/main/kotlin/Controller/RacingController.kt
> +    fun moveForward(car: Car): Int { // 뭔가 차량 별 능력 같은게 생기지 않을까 ㅇ3ㅇ
🚗

2023-12-11 23:16 UTC, pdg0704 commented on src/main/kotlin/Model/Car.kt
> +data class Car(val id: String)
자동차 이름이라던지 구분할 수 있는 무언가가 필요할 것 같아서 괜히 넣었습니다ㅎ

2023-12-11 23:17 UTC, pdg0704 commented on src/test/kotlin/Controller/RacingControllerTest.kt
> +class RacingControllerTest {
👍👍👍

2023-12-12 11:42 UTC, wdj4606 approved these changes
동근님 피드백 반영 너무 잘해주셨습니다 👍 
머지할테니 다음단계 진행해주세요!

2023-12-12 11:42 UTC, wdj4606 commented on src/main/kotlin/Main.kt
> +}
아주 좋습니다! 이제 main함수에서는 도메인 로직에 관하여 분리로 인하여 테스트 코드도 작성할 수 있는 형태가 되고 main에서는 해당 도메인들에 대해서만 호출하는 형태로 되었네요!

2023-12-12 11:42 UTC, merged