Step3- 테스트코드를 이걸 어케 짜지...
wdj4606/kotlin-racingcar pull request #37
Opened 2023-12-11 11:53 UTC by 00rigin

2023-12-11 12:24 UTC, wdj4606 requested changes
쭈니! 3단계 구현 잘해주셨네요! 👍 
몇가지 피드백 남겼으니 확인부탁드려요!

2023-12-11 12:24 UTC, wdj4606 commented on src/main/kotlin/step3/Cars.kt
> +class Cars(quantity: Int) {
일급컬렉션 너무 좋습니다! 👍

2023-12-11 12:24 UTC, wdj4606 commented on src/main/kotlin/step3/Cars.kt
> +    }
자동차에 숫자가 중간에 과연 변화를 할까요?  처음 생성될때 quantity를 통하여 Car객체를 생성하고 끝일거 같은데 List로 만들어서 불변을 지켜주는게 좋지 않을까용?? 🤔 
만약 불변으로 만든다면 이러하게 사용할 수 있을거 같네요
`val cars: List<Car> = List(quantity) { Car() }`

2023-12-11 12:24 UTC, wdj4606 commented on src/main/kotlin/step3/Cars.kt
> +            if (RandomUtil.isGoForward()) {
indent가 2입니다! 추상화 시켜주세요!
그리고 해당 for문은 forEach를 사용해도 좋을거 같습니다!

2023-12-11 12:24 UTC, wdj4606 commented on src/main/kotlin/step3/RacingData.kt
> +class RacingData(
음...현재 InputView Object와 순환참조가 걸려있는거 같네요 ㅋㅋㅋ
어차피 InputView는 Object클래스이기 때문에, main함수 사용하는 곳에서 그냥 바로 인라인으로 불러도 무방할 거 같습니다.

2023-12-11 12:24 UTC, wdj4606 commented on src/main/kotlin/step3/RandomUtil.kt
> +    fun isGoForward(): Boolean {
자동차가 움직일수 있냐라는 형태에 함수가 Util클래스로 있는게 맞을까요? 🤔 
어떻게 보면 Car가 가지고 있어야하는 책임이라던가, 혹은 Cars가 가지고 있어야하는 책임이지 않을까요??

2023-12-11 12:24 UTC, wdj4606 commented on src/main/kotlin/step3/ResultView.kt
> +object ResultView {
입출력 로직에 해당하는 부분을 도메인 로직과 분리를 아주 잘해주셨네요! 👍

2023-12-11 12:24 UTC, wdj4606 commented on src/test/kotlin/step3/CarsTest.kt
> +    }
전진이 있으면 멈추는것도 있으면 좋을거 같네요!

2023-12-11 12:31 UTC, 00rigin commented on src/test/kotlin/step3/CarsTest.kt
> +    }
저에게는 전진만 있을뿐... 정지란 없습니다.

2023-12-12 11:48 UTC, wdj4606 approved these changes
쭈니! 피드백 반영 잘해주셨습니다 ㅎㅎ 
머지할테니 다음단계 진행해주세요!

2023-12-12 11:48 UTC, wdj4606 commented on src/main/kotlin/step3/RacingGame.kt
> +        for (i in 1..InputView.inputTryCount()) {
값에 대해서의 반복문은 repeat함수를 사용하면 간결해질 수 있습니다!
```kotlin
repeat(InputView.inputTryCount()) {
    cars.goRoard()
```

2023-12-12 11:48 UTC, wdj4606 commented on src/main/kotlin/step3/ResultView.kt
> +        for (i in 1..car.distance) {
이부분도 repeat으로!

2023-12-12 11:48 UTC, merged