[step2] 문자열 계산기
wdj4606/kotlin-racingcar pull request #40
Opened 2023-12-12 23:43 UTC by ymseoooooo

감사합니다

2023-12-13 11:13 UTC, wdj4606 requested changes
하디! 구현 너무 잘해주셨네요! 👍 
몇가지 피드백 남겼으니 확인부탁드려요!

2023-12-13 11:13 UTC, wdj4606 commented on src/main/kotlin/step2/model/Calculator.kt
> +        if (formula.isNullOrBlank()) throw IllegalArgumentException("formula is null or blank")
if문을 통하여 exception을 던지는 형태로 만들어주셨는데요.
코틀린에선 `require()` 함수를 제공합니다!

`require(!formula.isNullOrBlank()) { "formula is null or blank" }`

2023-12-13 11:13 UTC, wdj4606 commented on src/main/kotlin/step2/model/Calculator.kt
> +        var result = splitFormulas[0].toInt()
만약 첫번째 값이 숫자가 아닐경우엔 어떻게 될까요? 🤔

2023-12-13 11:13 UTC, wdj4606 commented on src/main/kotlin/step2/model/OperatorType.kt
> +    DIVIDE("/", DivideOperation());
해당 부분에 있어서 연산자들은 모두 클래스로 분리해주셨는데용 이러한 방법도 아주 좋습니다!
그치만 람다를 이용하여 사용하면 좀 더 간결히 만들 수 있고, 여러 클래스도 생성을 안해도 됩니다!
```kotlin
enum class OperatorType(val operator: String, private val operation: (Int, Int) -> Int {
    ADDITION("+", { a , b -> a + b } ),

```

2023-12-13 11:13 UTC, wdj4606 commented on src/main/kotlin/step2/model/OperatorType.kt
> +            return values().find { it.operator == operator }
of함수로 찾는거 너무 좋습니다! 👍

2023-12-13 11:13 UTC, wdj4606 commented on src/main/kotlin/step2/model/Calculator.kt
> +    fun calculate(formula: String): Int {
현재 들어오는 값에 대해서 null처리가 안된거 같습니다! null이 들어올 수 있는 요구사항이 존재하기 때문에
타입을 `String?`로 받아야 하지 않을까용?

2023-12-13 11:13 UTC, wdj4606 commented on src/main/kotlin/step2/model/Calculator.kt
> +    private fun checkValidFormula(formula: String): Boolean {
마찬가지로 null을 받았을때에 대한 처리는 되어있고, 해당 값에 따라서 split이 진행을 한거 같습니다.
split을 통한 값을 유효성 검사가 통과가 된 이후, Boolean값을 반환하는 것이 아닌, 해당 split된 값을 반환해서 사용하는게 좋을거 같네요! 그래야 아래 코드에서 한번 더 split 할 필요가 없어질거 같습니다!

2023-12-13 11:13 UTC, wdj4606 commented on src/test/kotlin/step2/CalculatorTest.kt
> +class CalculatorTest {
테스트 코드 꼼꼼히 짜주신거 너무 좋습니다 ㅎㅎ 😄

2023-12-14 23:43 UTC, ymseoooooo commented on src/main/kotlin/step2/model/Calculator.kt
> +        if (formula.isNullOrBlank()) throw IllegalArgumentException("formula is null or blank")
오... 이런게 있군요ㅋㅋㅋㅋ
감사합니다

2023-12-14 23:48 UTC, ymseoooooo commented on src/main/kotlin/step2/model/Calculator.kt
> +    private fun checkValidFormula(formula: String): Boolean {
네네 처음에 split 한걸 return해서 사용하려다가 checkValidFormula 함수에 맞지 않는 동작인 것 같아서
한 번더 split을 한거였는데 수정하겠습니다 ㅎㅎ

2023-12-14 23:48 UTC, ymseoooooo commented on src/main/kotlin/step2/model/Calculator.kt
> +        var result = splitFormulas[0].toInt()
toInt() 과정에서 정수형으로 변경할 수 없는 경우 코틀린내부에서 에러를 뱉는다고 봤습니다!

2023-12-14 23:48 UTC, ymseoooooo commented on src/main/kotlin/step2/model/OperatorType.kt
> +    DIVIDE("/", DivideOperation());
처음에 람다로 구현하다가 클래스로 분리하는것이 OOP에 더 적합하다고 생각해서 분리한 것 같습니다~!
(지금은 사칙연산이지만 확장성을 위해..?)

2023-12-15 01:07 UTC, wdj4606 commented on src/main/kotlin/step2/model/Calculator.kt
> +        var result = splitFormulas[0].toInt()
논리적인 에러에 관련해서 개발자가 잡을 수 있을 경우는 잡아주는게 좋습니다! 그래야 실패원자성도 지킬 수 있는 형태가 될거니깐요! 만약 Int타입이 아닌 상태에서 저장을 하고 변환을 할때 컴파일러에 의존하여 실패를 하는거 보단, Int값이 아닌값이 들어왔을 때 exception을 던지는 형태가 좀 더 명확해지기 때문입니다! 딱히 문제는 없으니 넘어가도록 하죠!

2023-12-15 01:09 UTC, wdj4606 commented on src/main/kotlin/step2/model/OperatorType.kt
> +    DIVIDE("/", DivideOperation());
뭐 취향차이인거 같습니다 ㅎㅎ 하디가 말한거처럼 클래스로 분리하는것과 람다로 분리하는거에 있어서 어떤게 OOP에 적합한지 생각했다는 것만으로도 아주 좋네요! 😄 enum으로 관리되는 녀석이라 람다를 사용하여 코드 작성을 줄일 수 있고, 이왕 해보는거 람다로 해봐도 좋을거 같애서 말씀드렸던 부분입니다! 지금 방법도 아주 좋습니다! 👍

2023-12-15 11:58 UTC, merged