Step4
wdj4606/kotlin-racingcar pull request #45
Opened 2023-12-15 11:59 UTC by mayomayo0623

스승의 은혜는 하늘 같네요!

2023-12-15 12:14 UTC, wdj4606 requested changes
대현님! 구현 너무 잘해주셨습니다! 👍 도메인 분리가까지 이제 너무 명확하게 해서
딱히 말씀드릴 내용이 많이 없네요! 얼마 안남았습니다! 화이팅입니다!
몇가지 피드백 남겼으니 확인부탁드려요!

2023-12-15 12:14 UTC, wdj4606 commented on src/main/kotlin/racingcar/service/Car.kt
> +    var position: Int = START_POSITION
코틀린 레이아웃 컨벤션은 프로퍼티 > 초기화 블록 > 부 생성자 > 함수 > 연관객체 순입니다!
https://kotlinlang.org/docs/coding-conventions.html#class-layout

2023-12-15 12:14 UTC, wdj4606 commented on src/main/kotlin/racingcar/service/RacingCar.kt
> +            carList.add(Car(carName))
자동차 이름을 받아서 해당 클래스에서 초기화 블록으로 초기화를 하고 있는데요.
아예 외부에서 List<Car>를 생성하여 생성자 프로퍼티로 List<Car>를 받아보는게 어떨까여? 🤔

2023-12-15 12:14 UTC, wdj4606 commented on src/main/kotlin/racingcar/ui/InputView.kt
> +        return value.split(",")
해당 콤마도 연관객체로 치환해주세요!

2023-12-15 12:14 UTC, wdj4606 commented on src/test/kotlin/step3/RacingCarTest.kt
>      fun car() {
현재 어떠한 테스트인지에 대한 네이밍이 모호한거 같습니다. 어떠한 로직을 테스트 하고있는지에 대해서 명확하게 표현해주시면 좋을거같애요!

2023-12-15 12:14 UTC, wdj4606 commented on src/test/kotlin/step3/RacingCarTest.kt
> +            val car = Car("test")
마찬가지로 carName를 주입하였을때 제대로 담기는지에 대한 테스트도 있으면 좋을거같군요!

2023-12-15 12:14 UTC, wdj4606 commented on src/test/kotlin/step3/RacingCarTest.kt
> +            assert(numberOfRound >= it.position)
해당 하나의 테스트코드의 여러 도메인 로직이 섞여있는 형태인거같습니다. run 함수의 해당하는 테스트,
Winner에 해당하는 테스트가 분리되어야할거 같애요!
그리고 명확하게 명시해주는게 좋을거 같습니다. 
 ```
a자동차는 현재 position이 4, b자동차는 현재 position이 3일때,
우승자는 a이다.
``` 
이러한 명확한 테스트 코드가 있으면 좋을거같습니다!

2023-12-19 12:15 UTC, mayomayo0623 commented on src/test/kotlin/step3/RacingCarTest.kt
> +            assert(numberOfRound >= it.position)
@wdj4606 스승님! 테스트 코드 작성 훈련이 안되어 있다 보니, 말씀해 주신 대로 작성하기가 어렵네요ㅠ
일단 제 나름대로 작성은 해 보았는데, 스승님이 의도하신 바는 아닐 것 같습니다.

2023-12-19 12:25 UTC, wdj4606 approved these changes
테스트코드 작성하시는게 어려움이 있으신거 같네요 ㅋㅋㅋ 이번 단계 피드백 반영은 된거같아 머지할테니 다음단계에서 좀 더 자세하게 진행해보면 좋을거같습니다!

2023-12-19 12:25 UTC, merged