Step4
wdj4606/kotlin-racingcar pull request #46
Opened 2023-12-17 07:32 UTC by leejuhanKr

## 기능 요구 사항

초간단 자동차 경주 게임을 구현한다.

- 각 자동차에 이름을 부여할 수 있다. 자동차 이름은 5자를 초과할 수 없다.
- 전진하는 자동차를 출력할 때 자동차 이름을 같이 출력한다.
- 자동차 이름은 쉼표(,)를 기준으로 구분한다.
- 자동차 경주 게임을 완료한 후 누가 우승했는지를 알려준다. 우승자는 한 명 이상일 수 있다.

2023-12-19 11:28 UTC, wdj4606 requested changes
주한님! 4단계 구현 너무 잘해주셨습니다! 👍 
몇가지 피드백 남겼으니 확인부탁드립니다!

2023-12-19 11:28 UTC, wdj4606 commented on src/main/kotlin/racingcar/controller/GameController.kt
> +        inputView.run {
함수 호출들에 대해서 run 스코프 함수 사용해주셨는데요. 기본적으로 스코프 함수에 용도는 마지막으로 호출된 값에 대한 부분에 있어서 특정 동작을 실행하기 위한 목적으로 사용이 많이 됩니다. 
현재 만들어주신 부분으로 보았을때는 같은 객체에 대한 함수끼리 묶어서 진행한 느낌이 납니다. 그리고 run 함수일 경우에는 마지막으로 수행한 동작에 대한 반환 값을 기대하여 사용되는 경우에 사용이 됩니다.

2023-12-19 11:28 UTC, wdj4606 commented on src/main/kotlin/racingcar/model/Car.kt
> +    private val movableStrategy: MovableStrategy = MovableStrategy { true },
자동차라는 객체에 기본 전략은 랜덤전략이지 않을까요?

2023-12-19 11:28 UTC, wdj4606 commented on src/main/kotlin/racingcar/model/Cars.kt
> +            return Cars().apply {
apply를 사용해주셔도 좋지만, 특별한 초기화 로직이 없을경우엔, 인라인으로 생성자 호출하는게 가독성에 더 좋아보입니다!

2023-12-19 11:28 UTC, wdj4606 commented on src/main/kotlin/racingcar/model/Race.kt
> +        }
해당 부분에 있어서 Race라는 클래스에 최대 position값을 가져와 cars를 가져오는 도메인 로직으로 보입니다.
이러한 부분으로 작성해주셨으면, Race 클래스에 해당하는 테스트 코드 또한 존재해야할거 같네요! 
현재 race를 하는 함수, Winner를 가려내는 함수 등을 가지고 있는 Race라는 클래스가 도메인으로 존재해야하는지를 고민해보시면 좋을거 같습니다!

2023-12-19 11:28 UTC, wdj4606 commented on src/main/kotlin/racingcar/view/InputView.kt
> +            ?.replace(" ", "")
해당하는 replace는 결국 모든 빈칸은 없애는 행위를 하는 형태인거 같네요. 양쪽 공백만 없애고 싶으면 trim() 함수를 사용해보는게 좋을거같습니다! 만약 이름에 빈칸이 들어가는 형태일땐 예상치 못한 출력값이 나올 수 있을거같습니다! 그리고 입력값이 논리적인 오류일 경우엔 빈값을 반환하는게 아닌, exception을 던지는 형태가 좋습니다!

2023-12-19 11:28 UTC, wdj4606 commented on src/test/kotlin/racingcar/model/CarsTest.kt
> +})
현재 주어진 값에 통하여 given절을 재활용하시는 형태로 해주셨는데, 좀 더 명확한 테스트 코드를 위해서 분리해주시는건 어떨까요? 주어진 값이 서로 다른 형태로 주어지고 when절을 통하여 실제 코드를 실행하고 단언하는 형태가 되면 좋을거 같습니다!

2023-12-19 11:28 UTC, wdj4606 commented on src/test/kotlin/racingcar/model/RandomMovableStrategyTest.kt
> +        (0..4).forEach { randomValue ->
0..3까지가 움직이지 않는 형태입니다!

2023-12-19 11:28 UTC, wdj4606 commented on src/test/kotlin/racingcar/model/RandomMovableStrategyTest.kt
> +        }
해당 부분에 대해 mock객체로 사용해주셨는데요. 현재 0..4, 5..9까지 리스트라는 값에 대해서 불필요한 테스트 코드가 반복적으로 실행되고 있는 형태입니다.
5..9까지 리스트 중에 랜덤으로 뽑아낸 값을 통하여 mock객체에 randomValue를 stubbing 하는 형식은 어떨까요?
```kotlin
val randomValue = (5..9).toList().random()
val mock = spyk<RandomMovableStrategy>()
            every { mock["generateRandomNumber"]() } returns randomValue

            `when`("isMovable is called with random number $randomValue") {
                val result = mock.isMovable()

                then("it should return true") {
                    result shouldBe true
                }
            }
```

2023-12-21 00:35 UTC, jin-eden commented on src/main/kotlin/racingcar/controller/GameController.kt
> +        inputView.run {
제가 run 함수를 사용한 의도는 아래의 효과를 가지기 위해서 사용했습니다.
> run 함수는 확장 함수이기 때문에 context object를 receiver(this)로 이용할 수 있다.

또한 *inputView를 사용하여 race와 tryCount를 계산하는 것을 하나의 트랜잭션으로 생각했다*는 개발자의 의도를 나타내려고 했습니다.

하지만 이번에 조금 더 고민해보니 동재님 말씀대로 run함수는 *반환값을 기대하는 경우 사용된다*는 점에서 적절하지 않은 면이 있는 것 같습니다.
대신 with함수로 대체하면 어떨까 합니다. 
> with()는 람다의 결과가 필요하지 않고 객체에 대한 함수를 호출해야할 때 사용할 것을 권장한다. 코드에서 with 는 " with this object, do the following"이라고 읽으면 된다.    

 with을 사용하면 run에서 기대했던 효과를 누리면서도 일반적인 사용법에도 부합하는 것 같아 run 대신 with으로 대체하려고 합니다.

2023-12-21 00:35 UTC, jin-eden commented on src/main/kotlin/racingcar/model/Car.kt
> +    private val movableStrategy: MovableStrategy = MovableStrategy { true },
수정 완료했습니다!

2023-12-21 00:35 UTC, jin-eden commented on src/main/kotlin/racingcar/model/Cars.kt
> +            return Cars().apply {
변경 완료했습니다!

2023-12-21 00:35 UTC, jin-eden commented on src/main/kotlin/racingcar/model/Race.kt
> +        }
와..... 제가 딱 고민했던 부분입니다..!

저는 아래에 이유에서 Race 클래스가의 분리가 필요하다고 생각했습니다. 혹시 잘못생각한 부분이 있을까요..?
- Cars 클래스의 목적은 자동차들의 관리하는 일급 컬렉션으로써의 클래스 (경주와는 관련 없음)
- Race 클래스의 목적은 자동차의 경주의 전반을 관리하는 클래스
- controller클래스의 목적은 UI와 경주로직을 이어주는 클래스

그래서 이전 코드에서 없던 Cars라는 일급 컬렉션의 필요성을 느끼고 race에서 Cars를 분리해냈습니다.
분리해내고 나니 Race가 하는 일이 모호해지긴 했습니다.
그래서 Race를 controller와 합칠까  Cars와 합칠까 고민도 해보긴 했습니다.
합친다면 어디에 합치는 게 좋을까요...?

2023-12-21 00:35 UTC, jin-eden commented on src/main/kotlin/racingcar/view/InputView.kt
> +            ?.replace(" ", "")
수정 완료 했습니다!

2023-12-21 00:35 UTC, jin-eden commented on src/test/kotlin/racingcar/model/CarsTest.kt
> +})
수정 완료했습니다!

2023-12-21 00:35 UTC, jin-eden commented on src/test/kotlin/racingcar/model/RandomMovableStrategyTest.kt
> +        (0..4).forEach { randomValue ->
헛.... 수정 완료했습니다.

2023-12-21 00:35 UTC, jin-eden commented on src/test/kotlin/racingcar/model/RandomMovableStrategyTest.kt
> +        }
*5..9까지 리스트 중에 랜덤으로 뽑아낸 값을 통하여 mock객체에 randomValue를 stubbing 하는 형식* 을 제안해 주셨는데요..
그럴 경우 테스트가 랜덤값에 의해 좌우되기 때문에 부정확해진다고 생각합니다..

제가 만약 로직을 잘못짜서 ~(실제로도 잘못짜긴 했지만)~ 7부터 움직이도록 짰다고 가정했을 때 작성해주신 코드는 테스트에서 실패해야합니다.
`randomValue`가 5가 나오면 테스트를 실패하지만, 9가 나오면 테스트롤 통과하게 됩니다. 즉, 같은 test임에도 실행마다 결과가 달라질 수 있습니다.

저는 이러한 이유에서 0..9까지의 랜덤값을 리턴하는 것이 명확한 `generateRandomNumber`를 mocking했고, 
리턴값의 모든 경우에서 나머지 method들에 대해 테스트를 진행하려고 의도했습니다!

2025-11-28 16:50 UTC, leejuhanKr commented
동재님 잘 지내고 계신가요..? pr 정리하다보니 요 pr이 있었네용 ㅋㅋㅋ

2026-01-06 06:34 UTC, wdj4606 commented
ㅋㅋㅋㅋ 주한님 이제 봤네요 전 잘지내고 있습니다. 잘지내고 계신가여?? 이 pr은 닫을게여 ㅋㅋㅋ

2026-01-06 06:35 UTC, wdj4606 approved these changes

2026-01-06 06:35 UTC, merged