Step2
wdj4606/kotlin-racingcar pull request #52
Opened 2024-07-06 13:25 UTC by phj0319

오우 첫 PR이요!

p.s. Step 1에서 빌드 에러 나는게 있어서 걍 같이 pr에 포함시켰어요!

2024-07-07 01:21 UTC, wdj4606 requested changes
홍진님! 아주 구현 잘해주셨습니다! 👍 
몇가지 피드백 남겼으니 확인 부탁드립니다!
테스트 코드 작성하신걸 보니, 함수 부분별로 테스트 코드를 작성하시고 싶어서 public으로 열러두고 테스트 코드를 작성해주신거 같은데, private으로 닫고 public에서 호출하고 있는 함수에서 테스트 코드를 여러개 작성해주신다고 생각해주시면 될거 같습니다!

2024-07-07 01:21 UTC, wdj4606 commented on src/test/kotlin/Calculator.kt
> +object Calculator {
object 클래스로 만들어주셨는데요! 아주 굿입니다!
object 클래스로 만든 이유를 알수 있을까요??
특징도 같이 설명해주시면 좋을거 같습니다 ㅎㅎ

2024-07-07 01:21 UTC, wdj4606 commented on src/test/kotlin/Calculator.kt
> +        var result = calcItems[0].toDouble()
코틀린과 자바에서는 정수형 계산에 Double형을 사용하면 정확한 계산이 되지 않습니다!

2024-07-07 01:21 UTC, wdj4606 commented on src/test/kotlin/Calculator.kt
> +            result = when (operator) {
indent가 2이상입니다! 1로 변경해주세요! 
함수 추상화해서 변경해주면 좋을거 같습니다!

2024-07-07 01:21 UTC, wdj4606 commented on src/test/kotlin/CalculatorTest.kt
> +class CalculatorTest {
테스트 코드 아주 굿입니다!

2024-07-07 01:21 UTC, wdj4606 commented on src/test/kotlin/FormulaParser.kt
> +    const val PLUS = "+"
수식 연산자를 object에서 const 객체로 관리하는 것으로 만들어주셨는데요.
만약 연산자가 하나 더 추가가 된다고 하면 어떻게 될까요?? 현재 코드상으로 분석해보았을땐,
1. const 추가
2. 정규식 변경
3. Calculator 클래스에 수식 추가

이렇게 보입니다. 
해당 부분을 enum으로 관리하고 enum클래스에서 계산식을 들고 있는 상태로 변경하였을땐 관리하는 방법이 어떻게 될까요??
둘 중 어느 방법이 효과적인지 고민해보고 판단해보시면 좋을거 같습니다!

2024-07-07 01:21 UTC, wdj4606 commented on src/test/kotlin/FormulaParser.kt
> +        if (formula == null) {
if문을 통하여 null일때 IllegalArgumentException을 던지는 부분으로 만들어 주셨는데요.
코틀린에선 `require` 이라는 문법을 제공합니다! 그리고 String에서 제공되는 함수 중 null값과 빈값을 체크할수 있는 `nullOrBlank()` 함수도 제공합니다!
```kotlin
require (!formula.nullOrBlank()) { ERR_NULL_OR_EMPTY }
```

2024-07-07 01:21 UTC, wdj4606 commented on src/test/kotlin/FormulaParser.kt
> +    const val ERR_NULL_OR_EMPTY = "수식은 null이거나 비어있을 수 없음"
원시값 포장 아주 굿입니다! 👍

2024-07-07 01:21 UTC, wdj4606 commented on src/test/kotlin/FormulaParser.kt
> +    fun checkCharValid(formula: String) {
현재 함수들 중 FormulaParser 클래스 안에서만 사용되고 있는 함수들이 있는거 같습니다!
이러한 함수들은 접근자를 private로 만들어 주세요! 
private 함수는 테스트 코드를 작성안해주셔도 됩니다!
하지만 public 함수에서 해당 함수를 사용하고 있는 형태면 예외케이스로 테스트 코드를 구성해주시면 될거 같습니다!

2024-07-07 01:21 UTC, wdj4606 commented on src/test/kotlin/FormulaParser.kt
> +            splits.mapIndexed { index, value ->
이부분도 indent가 2이상입니다!

2024-07-07 01:21 UTC, wdj4606 commented on src/test/kotlin/FormulaParserTest.kt
> +        assertThatThrownBy {
예외 테스트 코드 아주 굿입니다!

2024-07-07 10:55 UTC, phj0319 commented on src/test/kotlin/Calculator.kt
> +object Calculator {
object를 통해서 불필요하여 여러면 인스턴스 여러번 생성하는 것을 막기 위해 처리했습니다!
object는 class와 달리 정의와 동시에 인스턴스 생성된다고 공부했습니다.

2024-07-08 13:11 UTC, phj0319 commented on src/test/kotlin/Calculator.kt
> +        var result = calcItems[0].toDouble()
BigDecimal로 수정했습니다!

2024-07-08 13:12 UTC, phj0319 commented on src/test/kotlin/Calculator.kt
> +            result = when (operator) {
요부분 함수화 했습니다!

2024-07-08 13:12 UTC, phj0319 commented on src/test/kotlin/FormulaParser.kt
> +    const val PLUS = "+"
enum class를 통해 계산식을 같이 들고 있는거 매우 편하군요!
gpt 에게 힌트를 얻어서 정규표현식도 같이 처리했습니다!

2024-07-08 13:13 UTC, phj0319 commented on src/test/kotlin/FormulaParser.kt
> +        if (formula == null) {
오... require 완전 제 취향입니다! 코드가 많이 간결해지는군요!

2024-07-08 13:13 UTC, phj0319 commented on src/test/kotlin/FormulaParser.kt
> +    fun checkCharValid(formula: String) {
private 처리 했습니다~
추가로 몇가지만 테스트 public 함수 쪽에 추가했어요!

2024-07-08 13:13 UTC, phj0319 commented on src/test/kotlin/FormulaParser.kt
> +            splits.mapIndexed { index, value ->
넵! 함수화 했습니다!

2024-07-08 13:18 UTC, wdj4606 commented on src/test/kotlin/Calculator.kt
> +object Calculator {
맞습니다! object는 싱글턴을 보장해줍니다! 해당 부분에 있어서 싱글턴이 보장이 되어야하는지 아닌지를 판단해서 사용해주신거 같애서 아주 좋습니다! 👍

2024-07-08 13:31 UTC, wdj4606 approved these changes
홍진님! 피드백 반영 잘해주셨습니다! 👍 
머지할테니 다음단계 진행해주시면 되겠습니다.
다음 단계 브랜치 step3따셔서 step3 pull request는 제가 다시 피드백 남긴 부분과 함께 같이 올려주시면 되겠습니다!

2024-07-08 13:31 UTC, wdj4606 commented on src/test/kotlin/Operator.kt
> +enum class Operator(val symbol: String, val operation: (BigDecimal, BigDecimal) -> BigDecimal) {
enum 클래스 아주 좋습니다!

2024-07-08 13:31 UTC, wdj4606 commented on src/test/kotlin/FormulaParser.kt
> +    private fun splitByOperator(formula: String): List<String> {
정규식으로 한번 걸러서 List<String>을 할 필요가 있을까요?? 🤔 
enum값으로 정의를 한 상태라 해당 문자열이 fromSymbol로 연산자를 불러오지 못하면 되는거 아닐까여??

2024-07-08 13:31 UTC, wdj4606 commented on src/test/kotlin/FormulaParser.kt
> +        require(operator in listOf(Operator.PLUS, Operator.MINUS, Operator.MULTIPLY, Operator.DIVIDE)) { ERR_OPERATOR_STRING }
Operator enum 클래스의 요소들이 아니면 ERR를 뱉는 로직은 이 object 클래스의 책임이 아닌
enum 클래스에 있어야하는 책임으로 보입니다. 해당 로직을 fromSymbol 로직으로 위임할 수 있을것으로 보입니다!

2024-07-08 13:31 UTC, wdj4606 commented on src/test/kotlin/Operator.kt
> +            return values().find { it.symbol == symbol }
코틀린에선 해당 값이 null일 경우엔 오른쪽 값이 반환되고 null이 아닐경우엔 왼쪽값이 반환되게 제공해주는 
`?:`(엘비스 연산자)가 있습니다.
해당 연산자로 로직을 위임할 수 있을거같네요!
```kotlin
fun fromSymbol(symbol: String): Operator {
   return values().find { it.symbol == symbol } ?: throws IlliegalArgumentException(ERR_OPERATOR_STRING)
}
```

2024-07-08 13:31 UTC, wdj4606 commented on src/test/kotlin/FormulaParserTest.kt
> +//    @Test
해당 주석된 테스트 코드를 실행할 수 있는 방법이 무엇이 있을까요? 🤔 
해당 부분은 고민해보시고, 아예 테스트 코드를 실행을 안하실꺼면 삭제해주세요!

2024-07-08 13:31 UTC, merged

2024-07-09 13:53 UTC, phj0319 commented on src/test/kotlin/FormulaParser.kt
> +    private fun splitByOperator(formula: String): List<String> {
음... 생각해보니 그러네요. 뒤에서 아마 예외처리된것에 걸릴 것이라 중복 체크를 할 필요를 없어 보이네요.
정규표현식을 통한 확인 코드는 제거하였습니다!

2024-07-09 14:02 UTC, phj0319 commented on src/test/kotlin/FormulaParser.kt
> +        require(operator in listOf(Operator.PLUS, Operator.MINUS, Operator.MULTIPLY, Operator.DIVIDE)) { ERR_OPERATOR_STRING }
오! 예리한 지적이네요! 옮기겠습니다

2024-07-09 14:04 UTC, phj0319 commented on src/test/kotlin/Operator.kt
> +            return values().find { it.symbol == symbol }
엘비스 연산자란게 있군요! 반영했습니다

2024-07-09 14:05 UTC, phj0319 commented on src/test/kotlin/FormulaParserTest.kt
> +//    @Test
테케 다시 살렸습니다!