Step3
wdj4606/kotlin-racingcar pull request #54
Opened 2024-07-10 11:31 UTC by phj0319

2024-07-10 13:02 UTC, wdj4606 requested changes
홍진님 3단계 구현 너무 잘해주셨습니다 👍 
몇가지 피드백 남겼으니 확인부탁드려요!

2024-07-10 13:02 UTC, wdj4606 commented on src/main/kotlin/CarRacing/InputView.kt
> +data class InputParameters(val numberOfCar: Int, val numberOfRace: Int)
data class로 하신 이유가 있을까요?? 🤔

2024-07-10 13:02 UTC, wdj4606 commented on src/main/kotlin/CarRacing/Race.kt
> +    val racingCars: List<RacingCar> = List(inputParameters.numberOfCar) { RacingCar() }
오 List 가짜 생성자 아주 굿입니다 ㅎㅎ 👍

2024-07-10 13:02 UTC, wdj4606 commented on src/main/kotlin/CarRacing/Race.kt
> +    fun tryRace() {
이 부분이 조금 이해가 안되네요. 🤔 외부에서 몇번 시도하는지에 대한 검증을 하고, 도메인 로직에서 수행하는 부분인데, 여기서 몇번 시도했는지를 한번 더 검증하는 이유가 있을까요? 
해당 코드처럼 몇번 시도했는지에 대한 횟수보다 currentTryCount가 넘을 수 있는 상황이 무엇이 있을까요?

2024-07-10 13:02 UTC, wdj4606 commented on src/main/kotlin/CarRacing/RacingCar.kt
> +        if (random >= 4)
우리가 프로그래밍 요구사항을 4이상으로 잡았는데, 만약 5이상으로 변경되어야한다고 하면 어떻게 될까요?
이 부분도 원시값 포장해주세요!

2024-07-10 13:02 UTC, wdj4606 commented on src/main/kotlin/CarRacing/RacingCar.kt
> +data class RacingCar(var progress: Int = 0) {
마찬가지로 움직이지 않는 처음 위치를 0으로 잡았지만 만약 1로 수정해야 한다는 요구사항이 들어왔을때도 있을수 있겠죠?

2024-07-10 13:02 UTC, wdj4606 commented on src/main/kotlin/CarRacing/main.kt
> +    repeat(inputParameters.numberOfRace) {
오 repeat함수 아주 좋습니다 ㅎㅎ 👍

2024-07-10 13:02 UTC, wdj4606 commented on src/test/kotlin/CarRacingInputViewTest.kt
> +class CarRacingInputViewTest {
프로그래밍 요구사항에도 명시되어 있지만, UI로직인 Input과 Output 로직에 테스트 코드는 제외해주세요!

2024-07-10 13:02 UTC, wdj4606 commented on src/test/kotlin/RaceTest.kt
> +    fun `자동차 경주 잘 진행되니?`() {
테스트 코드를 작성해 주실때 전반적인 BDD 프레임워크 구조를 사용하여 작성해주시는게 가독성에 좋습니다.
BDD 프레임워크에 기본적인 테스트 코드 구조는 given-when-then 구조입니다!
given : 주어지는 환경(변수나 mocking, stubbing)
when : 실제 행위(실제 함수 실행)
then : 기대 결과(단언 및 검증)
이 형태로 테스트 코드를 변경해주세요! 
간단한 예시를 보여드리겠습니다.
```kotlin
@Test
fun `자동차 경주 잘 진행되니?`() {
    //given
    val inputParameters = InputParameter(3,5)
    val race = Race(inputParameters)

    //when
    race.tryRace()

    //then
    race.racingCars.forEach { racingCar ->
            Assertions.assertThat(racingCar.progress).isLessThanOrEqualTo(1)
    }
}

```

2024-07-11 14:49 UTC, phj0319 commented on src/main/kotlin/CarRacing/InputView.kt
> +data class InputParameters(val numberOfCar: Int, val numberOfRace: Int)
UI를 위해 주고받는 것은 데이터로 처리하고 싶어서 그랬습니다.
원래는 pair로 처리하려다가 input이 여러가지가 될 가능성이 있어서 미리 데이터 클래스로 처리해두었습니다

2024-07-11 14:54 UTC, phj0319 commented on src/main/kotlin/CarRacing/Race.kt
> +    fun tryRace() {
음 그러네요 요건 좀 과한 코드인 것 같아 보입니다. 불필요해보이므로 제거하겠습니다!

2024-07-11 14:56 UTC, phj0319 commented on src/main/kotlin/CarRacing/RacingCar.kt
> +        if (random >= 4)
넵 반영하겠습니다

2024-07-11 14:56 UTC, phj0319 commented on src/main/kotlin/CarRacing/RacingCar.kt
> +data class RacingCar(var progress: Int = 0) {
넵 반영하겠습니다

2024-07-11 15:03 UTC, phj0319 commented on src/test/kotlin/CarRacingInputViewTest.kt
> +class CarRacingInputViewTest {
넵 제거하겠습니당

2024-07-11 15:08 UTC, phj0319 commented on src/test/kotlin/RaceTest.kt
> +    fun `자동차 경주 잘 진행되니?`() {
아 테스트도 요렇게 하는게 좋겠네요!
반영하겠습니다!

2024-07-12 04:16 UTC, wdj4606 approved these changes
홍진님! 구현잘해주셨습니다! 머지할테니 다음 단계에 현재 피드백과 같이 진행해주시면 되겠습니다!

2024-07-12 04:16 UTC, wdj4606 commented on src/main/kotlin/CarRacing/InputView.kt
> +data class InputParameters(val numberOfCar: Int, val numberOfRace: Int)
맞습니다. 값을 전달하거나 처리하는데에 목적을 두고 data class를 사용하시는건 좋아보입니다. 하지만 지금 홍진님이 만드신 클래스들을 전부 data class로 만들어주셔서 질문했던 부분이였습니다. 도메인의 해당하는 클래스들이 값만 전달하는 클래스가 아니기 때문에 해당 부분은 일반 클래스로 관리해주시는게 좋습니다!

2024-07-12 04:16 UTC, wdj4606 commented on src/test/kotlin/RaceTest.kt
> +            Assertions.assertThat(racingCar.progress).isLessThanOrEqualTo(inputParameters.numberOfRace)
현재 tryRace()를 통하여 전진 했는지 안했는지에 대한 정확한 판단이 되지 않는 상태로 테스트가 작성되고 있습니다. 만약 정확히 move했다!라는 테스트 코드를 작성할 수 있는 방법은 무엇이 있을까요? 🤔

2024-07-12 04:16 UTC, wdj4606 commented on src/main/kotlin/CarRacing/RacingCar.kt
> +        val random = Random.nextInt(RANDOM_STT, RANDOM_END)
현재 자동차 객체가 움직이는데에 로직은 0-9의 숫자를 랜덤으로 뽑아서 움직이는 형태로 구성해주셨는데요. 자동차가 움직이는데 4이상인 경우는 도메인 로직이겠지만, 이 자동차가 0~9까지 랜덤으로 뽑는걸 알 필요가 있을까요? 🤔 자동차 입장에선 들어온 값에 대해서 4이상이냐만 판단하면 되는거니깐요 ㅎㅎ

2024-07-12 04:17 UTC, merged

2024-07-13 15:51 UTC, phj0319 commented on src/main/kotlin/CarRacing/InputView.kt
> +data class InputParameters(val numberOfCar: Int, val numberOfRace: Int)
요 코멘트가 조금 이해가 안되는데,
InputParameters는 도메인에 해당하는 클래스이니, 일반 클래스로 바꿔달라는 말씀이실까용?

2024-07-13 16:03 UTC, phj0319 commented on src/main/kotlin/CarRacing/RacingCar.kt
> +        val random = Random.nextInt(RANDOM_STT, RANDOM_END)
차가 가는 것은 결국 엔진이 동작 하냐 안하냐라고 생각해서 랜덤의 내용은 CarEngine 클래스를 만들어서 위임했습니다!

2024-07-13 16:33 UTC, phj0319 commented on src/test/kotlin/RaceTest.kt
> +            Assertions.assertThat(racingCar.progress).isLessThanOrEqualTo(inputParameters.numberOfRace)
mockk를 활용하는 것이 방법이 될까요? 그렇게 테스트 케이스 추가하겠습니다!
p.s. 뭐를 요구하신지 몰라서 한참 고민하다가 다른분들 코드리뷰 보고 힌트가 된것 같기도...ㅎㅎ

2024-07-14 00:36 UTC, wdj4606 commented on src/main/kotlin/CarRacing/InputView.kt
> +data class InputParameters(val numberOfCar: Int, val numberOfRace: Int)
맞습니다 제가 너무 이 부분에 대해서 이야기하는거처럼 답변을 했었군요
홍진님이 이해하신게 맞습니다!

2024-07-14 00:36 UTC, wdj4606 commented on src/test/kotlin/RaceTest.kt
> +            Assertions.assertThat(racingCar.progress).isLessThanOrEqualTo(inputParameters.numberOfRace)
ㅋㅋㅋㅋㅋ 이부분은 고민해보시는게 좋을거같네요