Step4
wdj4606/kotlin-racingcar pull request #57
Opened 2024-07-13 17:15 UTC by phj0319

2024-07-14 00:51 UTC, wdj4606 requested changes
홍진님! 4단계 구현 너무 잘해주셨습니다 😄 
점점 코틀린에 익숙해지시는게 보이네요ㅎㅎ
몇가지 피드백 남겼으니 확인 부탁드려요!

2024-07-14 00:51 UTC, wdj4606 commented on src/main/kotlin/CarRacing/CarEngine.kt
> +const val RANDOM_STT = 0
해당 const값은 최상위로 작성해주셨는데, 이렇게 되버리면 다른 클래스에게까지 전파가 될 위험이 있습니다.
RANDOM_STT와 RANDOM_END는 여기 CarEngine에서만 사용하는 클래스처럼 보이는데, 이럴땐 클래스에 연관객체로 만들어주시면 됩니다.
```kotlin
class CarEngine {
    fun isRuannable(): Boolean {
    }
    
    companion object {
        private const val RANDOM_STT = 0
        private const val RANDOM_END = 9
    }
}

```

2024-07-14 00:51 UTC, wdj4606 commented on src/main/kotlin/CarRacing/CarEngine.kt
> +class CarEngine {
변수를 가지고 있지 않는 클래스인거 같은데, 이럴땐 object클래스를 써서 싱글턴을 보장해주는게 좋지 않을까요?

2024-07-14 00:51 UTC, wdj4606 commented on src/main/kotlin/CarRacing/InputView.kt
> +        require(input != null) { ERR_INPUT_CAR_NAMES }
requireNotNull()이라는 함수가 있습니다!
```kotlin
requireNotNull(input) { ERR_INPUIT_CAR_NAMES }
```

2024-07-14 00:51 UTC, wdj4606 commented on src/main/kotlin/CarRacing/InputView.kt
> +        val carNames = input.split(",").map { it.trim() }
해당 콤마도 치환해주세요!

2024-07-14 00:51 UTC, wdj4606 commented on src/main/kotlin/CarRacing/InputView.kt
> +            require(name.length <= 5) { ERR_NAME_LENGTH }
자동차 이름이 5이하여야 한다는 로직을 Input의 로직일까요? 🤔 
이 부분도 역시 도메인 로직 중 하나로 보이는데, UI를 담당하는 클래스에선 도메인 로직에 의존되면 안됩니다!
적절한 도메인에 위임해주세요!

2024-07-14 00:51 UTC, wdj4606 commented on src/main/kotlin/CarRacing/Race.kt
> +class Race(carNames: List<String> = List(3) { "pobi" }, val racingCars: List<RacingCar> = carNames.map { RacingCar(it) }) {
Race클래스는 carNames의 리스트를 가지고 있는 이유가 무엇인가요?? 🤔

2024-07-14 00:51 UTC, wdj4606 commented on src/main/kotlin/CarRacing/RacingCar.kt
> +class RacingCar(val carName: String = NA_NAME, var progress: Int = INITIAL_PROGRESS, val carEngine: CarEngine = CarEngine()) {
기본 인자 함수 사용 아주 잘 활용해주시는게 좋네요 ㅎㅎ 😄

2024-07-14 00:51 UTC, wdj4606 commented on src/test/kotlin/CarEngineTest.kt
> +    fun `러너블 할 때`() {
isRunnable()함수에서 Boolean값을 판단하는 테스트를 모킹밖에 없을까요? 만약 외부에서 값을 받아서 true / false를 판단할 수 있는 형태로 변경한다면 모킹없이 할 수 있지 않을까요?

2024-07-14 00:51 UTC, wdj4606 commented on src/test/kotlin/RaceTest.kt
> +            Assertions.assertThat(racingCar.progress).isEqualTo(inputParameters.numberOfRace)
단언 검증하는 부분에 값이 조금 위험해보일수 있네요. 시행한 횟수와 position에 값이 동일하냐?에 대한 검증으로 해주신거 같은데, 만약 position이 2씩 증가된다고 하면, 해당 테스트 코드는 실패하게 될것입니다. 
현재 만들어주신 테스트 코드는 모든 CarEngine을 움직이는 형태로 만들어주셨는데, 이럴 경우엔 모든 차가 포지션이 동일하지 않을까요? 이러한 형태로 검증하는게 좋아보입니다!

2024-07-14 00:51 UTC, wdj4606 commented on src/test/kotlin/RaceTest.kt
>  class RaceTest {
우승자에 대한 테스트 코드가 빠진거 같습니다! 경주 이후 우승자를 뽑아내는 테스트 코드 작성해주세요!

2024-07-14 13:25 UTC, phj0319 commented on src/main/kotlin/CarRacing/CarEngine.kt
> +const val RANDOM_STT = 0
넵 섬세한 은닉성 좋네요!

2024-07-14 13:29 UTC, phj0319 commented on src/main/kotlin/CarRacing/CarEngine.kt
> +class CarEngine {
CarEngine이 지금은 단순히 랜덤으로 실행가능성을 판단하는 함수만 있긴 하지만,
차량은 모두 엔진을 가지고 있는것이 자연스럽다고 느껴져서 object로 처리하지 않았습니다.

그래서 다음 두가지 중에 하나를 선택하는것이 좋아보이는데, 어떻게 생각하시나요?
1. 현재처럼 차는 각각의 CarEngine 객체를 가지고 있도록 하기 위해 object가 아닌 class로 처리
2. 그냥 랜덤 함수를 관리하는 별도의 Util 기능을 제공하는 것으로 object로 바꾸고 혼동 방지를 위해 이름도 바꿈 (ex. object RunnableChecker)

2024-07-14 13:30 UTC, phj0319 commented on src/main/kotlin/CarRacing/InputView.kt
> +        require(input != null) { ERR_INPUT_CAR_NAMES }
정말 웬만한건 다 키워드와 함수가 있군요ㄷㄷ 반영하겠습니다!

2024-07-14 13:31 UTC, phj0319 commented on src/main/kotlin/CarRacing/InputView.kt
> +        val carNames = input.split(",").map { it.trim() }
오 꼼꼼하십니다..ㅎㅎ 반영했습니다!

2024-07-14 13:41 UTC, phj0319 commented on src/main/kotlin/CarRacing/InputView.kt
> +            require(name.length <= 5) { ERR_NAME_LENGTH }
넵  도메인쪽으로 이동하겠습니다!

2024-07-14 13:46 UTC, phj0319 commented on src/main/kotlin/CarRacing/Race.kt
> +class Race(carNames: List<String> = List(3) { "pobi" }, val racingCars: List<RacingCar> = carNames.map { RacingCar(it) }) {
carNames앞에 val을 붙이지 않음으로서 클래스가 해당 변수를 가지고 있지는 않지만,
생성자로서 carNames만 받아서 Race가 RacingCar 객체를 생성하도록 처리했는데 음.. 보다보니 어색한 느낌이네요..

RacingCar만 생성자로서 받도록 수정하겠습니다!

2024-07-14 13:58 UTC, phj0319 commented on src/test/kotlin/CarEngineTest.kt
> +    fun `러너블 할 때`() {
음 요건 어떤 것을 말씀하시는지 잘 이해가 안되는데 예시코드를 보여주실 수 있을까요..?

2024-07-14 14:01 UTC, phj0319 commented on src/test/kotlin/RaceTest.kt
> +            Assertions.assertThat(racingCar.progress).isEqualTo(inputParameters.numberOfRace)
오 그런 접근도 가능하겠군요! 반영하겠습니다!

2024-07-14 14:11 UTC, phj0319 commented on src/test/kotlin/RaceTest.kt
>  class RaceTest {
아 넵 우승자 테케 추가하겠습니다!

2024-07-14 23:02 UTC, wdj4606 approved these changes
홍진님 4단계 피드백 반영 너무 잘해주셨습니다 ㅎㅎ
머지할테니 다음단계 진행해주세요!

2024-07-14 23:02 UTC, wdj4606 commented on src/main/kotlin/CarRacing/CarEngine.kt
> +    companion object {
코틀린에서 레이아웃 컨벤션은 
프로퍼티(val / var) > 초기화 블록(init) > 함수(fun) > 연관 객체(companion object) 순입니다!
[코틀린 레이아웃 컨벤션](https://kotlinlang.org/docs/coding-conventions.html#class-layout)

2024-07-14 23:02 UTC, wdj4606 commented on src/main/kotlin/CarRacing/RacingCar.kt
> +    companion object {
여기도 마찬가지로 레이아웃 컨벤션을 지켜주세요!

2024-07-14 23:02 UTC, merged

2024-07-15 03:48 UTC, phj0319 commented on src/main/kotlin/CarRacing/CarEngine.kt
> +    companion object {
넵 적용하겠습니다!

2024-07-15 03:48 UTC, phj0319 commented on src/main/kotlin/CarRacing/RacingCar.kt
> +    companion object {
넵 적용하겠습니다!