Step3 피드백 및 Step4 PR
wdj4606/kotlin-racingcar pull request #58
Opened 2024-07-14 12:03 UTC by pcs0807

step3 피드백, step4 커밋분 포함입니다.
주말인데도 하나하나 챙겨주셔서 감사합니다!

2024-07-14 13:21 UTC, wdj4606 requested changes
찬석님! 4단계 구현 잘해주셨습니다! 👍 
몇가지 피드백 남겼으니 확인부탁드립니다!

2024-07-14 13:21 UTC, wdj4606 commented on src/main/kotlin/step3/Car.kt
> +private const val MOVE_CONDITION = 4
최상위 함수로 만들어주시는거 보단 각 클래스에 연관객체로 만들어 주시는게 좋습니다! 
```kotlin
class Car(var position : Int = INITIAL_POSITION) {
    companion object {
        private const val MOVE_CONDITION = 4
    }
}
```

2024-07-14 13:21 UTC, wdj4606 commented on src/main/kotlin/step4/RaceGame.kt
> +        fun validate(carName: String) {
RaceGame에서 carName을 리스트로 받고 Car클래스에서도 carName을 받고 있습니다. 중복으로 이름을 받는 이유가 있을까요?? 🤔 
그리고 자동차 이름이 5자를 초과한다는 유효성 검증을 RaceGame 클래스가 책임을 지는게 맞을까요? 
자동차 객체가 만들어질때 검증이 이루어져야하지 않을까요??

2024-07-14 13:21 UTC, wdj4606 commented on src/main/kotlin/step4/RaceGame.kt
> +            printCurrentPositions()
현재 도메인 로직에 출력 로직이 같이 의존되어 있습니다! 
도메인 로직에서 UI로직을 분리해주세요!

2024-07-14 13:21 UTC, wdj4606 commented on src/main/kotlin/step4/RaceGame.kt
> +            .maxOrNull()!!
마찬가지로 null일 이유가 없을거 같은데 이럴땐 `!!`연산자가 아닌 논리적 오류를 던져주세요

2024-07-14 13:21 UTC, wdj4606 commented on src/main/kotlin/step4/View.kt
> +    private val scanner = Scanner(System.`in`)
`readln()`가 아닌 system.in으로 찍은 이유가 있을까요?

2024-07-14 13:21 UTC, wdj4606 commented on src/test/kotlin/step4/RaceGameTest.kt
> +        val result = InputView.inputCarNames()
step3에서 말씀드렸던거 같은데, UI로직은 테스트 코드 제외입니다.

2024-07-15 11:34 UTC, pcs0807 commented on src/main/kotlin/step3/Car.kt
> +private const val MOVE_CONDITION = 4
네 참고하겠습니다.

2024-07-15 13:15 UTC, pcs0807 commented on src/test/kotlin/step4/RaceGameTest.kt
> +        val result = InputView.inputCarNames()
네
테스트 케이스가 너무 없는 것 같아서..

2024-07-15 13:27 UTC, wdj4606 approved these changes
찬석님! 피드백 반영 잘해주셨습니다!
앞으로 작업하실때, 기존 작성된 코드를 수정하는 형태로 작성해주세요.
step별로 새로 만들려고 하시면, 제가 보기도 불편하고 기존 피드백을 반영되는 부분에 대해서를 구분하기가 힘들어집니다 ㅠ
머지할테니, 다음 단계 진행해주세요!

2024-07-15 13:27 UTC, wdj4606 commented on src/main/kotlin/step3/Car.kt
> +    companion object {
코틀린에서 레이아웃 컨벤션은
프로퍼티(val / var) > 초기화 블록(init) > 함수(fun) > 연관 객체(companion object) 순입니다!
[코틀린 레이아웃 컨벤션](https://kotlinlang.org/docs/coding-conventions.html#class-layout)

2024-07-15 13:27 UTC, wdj4606 commented on src/main/kotlin/step3/RaceGame.kt
> +    private fun copyCars(cars: CarList): CarList {
이 CarList를 카피하는 로직은 CarList 클래스가 가지고 있는게 맞지 않을까요??

2024-07-15 13:27 UTC, wdj4606 commented on src/test/kotlin/step4/RaceGameTest.kt
> +        ResultView.printHistory(game.getRaceHistory())
해당 부분을 검증할 수 있는 부분이 print가 찍는것이 아닌, 정확한 검증을 할 수 있는 방법이 무엇이 있을까요?

2024-07-15 13:27 UTC, merged